<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Professor Noli Brazil" />

<meta name="date" content="2026-04-27" />

<title>Introduction to Spatial Data</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
      .display.math{display: block; text-align: center; margin: 0.5rem auto;}
  </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">GEO 200CN: Spring 2026</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
<li>
  <a href="hw_guidelines.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Labs
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="getting_started.html">Getting Started</a>
    </li>
    <li>
      <a href="data_transformation.html">Data Transformation</a>
    </li>
    <li>
      <a href="eda.html">Exploratory Data Analysis</a>
    </li>
    <li>
      <a href="inference.html">Statistical Inference</a>
    </li>
    <li>
      <a href="hypothesis.html">Hypothesis Testing</a>
    </li>
    <li>
      <a href="linearregression.html">Linear Regression</a>
    </li>
    <li>
      <a href="linearregression2.html">More Linear Regression</a>
    </li>
    <li>
      <a href="glm.html">Generalized Linear Models</a>
    </li>
    <li>
      <a href="introspatial.html">Intro to Spatial Data</a>
    </li>
    <li>
      <a href="pointpatterns.html">Point Pattern Analysis</a>
    </li>
    <li>
      <a href="spatialautocorrelation.html">Spatial Autocorrelation</a>
    </li>
    <li>
      <a href="spatialreg.html">Spatial Regression</a>
    </li>
    <li>
      <a href="prediction.html">Prediction Modelling</a>
    </li>
    <li>
      <a href="interpolation.html">Spatial Interpolation</a>
    </li>
    <li>
      <a href="kriging.html">Kriging</a>
    </li>
    <li>
      <a href="regtrees.html">Regression Trees</a>
    </li>
    <li>
      <a href="variableselection.html">Variable Selection</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="tips.html">R Tips</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Introduction to Spatial Data</h1>
<h3 class="subtitle"><font size="4">GEO 200CN - Quantitative
Geography</font></h3>
<h4 class="author">Professor Noli Brazil</h4>
<h4 class="date">April 27, 2026</h4>

</div>


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: normal;
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>
<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>
<p><br />
</p>
<p>This week you will learn how to process and map spatial data in R.
The two major packages for processing spatial data in R are
<strong>sf</strong> and <strong>terra</strong>. To motivate the use of
these packages, the bulk of the guide will focus on how to map data. The
objectives of this lab are as follows:</p>
<ol style="list-style-type: decimal">
<li>Learn how to read in and write vector and raster data</li>
<li>Learn vector and raster data transformation operations</li>
<li>Learn how to map vector and raster data</li>
</ol>
<p>Although the lab guide closely follows the OSU readings for this
week, some new concepts are introduced, so make sure to carefully read
the material.</p>
<div style="margin-bottom:25px;">

</div>
<div id="installing-and-loading-packages" class="section level2">
<h2><strong>Installing and loading packages</strong></h2>
<p><br />
</p>
<p>Install <strong>sf</strong> and <strong>terra</strong> if you have
not already done so.</p>
<pre class="r"><code>install.packages(c(&quot;sf&quot;, &quot;terra&quot;))</code></pre>
<p>We will also be using the packages <strong>tmap</strong>,
<strong>ggspatial</strong>, <strong>RColorBrewer</strong>,
<strong>maptiles</strong>, and <strong>cartogram</strong> in this
lab.</p>
<pre class="r"><code>install.packages(c(&quot;tmap&quot;, &quot;ggspatial&quot;, &quot;RColorBrewer&quot;, &quot;maptiles&quot;, &quot;cartogram&quot;))</code></pre>
<p>Load all of these packages using <code>library()</code>. We’ll also
be using the package <strong>tidyverse</strong>, so load it up as well.
Remember, you always need to use <code>library()</code> at the top of
your R Markdown files.</p>
<pre class="r"><code>library(sf)
library(terra)
library(tmap)
library(ggspatial)
library(tidyverse)
library(RColorBrewer)
library(maptiles)
library(cartogram)</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="spatial-data" class="section level2">
<h2><strong>Spatial data</strong></h2>
<p><br />
</p>
<p>Spatial phenomena can generally be thought of as either discrete
objects with clear boundaries or as a continuous phenomenon that can be
observed everywhere, but does not have natural boundaries. Discrete
spatial objects may refer to a river, road, country, town, or a research
site. Examples of continuous phenomena, or “spatial fields”, include
elevation, temperature, and air quality.</p>
<p>There are two general spatial data object types: Vector and Raster.
Vector data represent geographic features as discrete points, lines, or
polygons defined by precise coordinates. Raster data represent space as
a continuous grid of cells (pixels), where each cell stores a value
corresponding to a characteristic at that location. We discuss vector
and raster data types, and how they are processed in R, in turn.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="vector-data" class="section level2">
<h2><strong>Vector data</strong></h2>
<p><br />
</p>
<p>The main vector data types are points, lines and polygons. In all
cases, the geometry of these data structures consists of sets of
coordinate pairs (x, y), and normally also includes additional variables
often referred to as “attributes”. For example, a vector data set may
describe the borders of the countries of the world, and also store their
names and the size of their population; or the geometry of the roads in
an area, as well as their types and names; or a place where an animals
was tagged, and the attributes could include the date it was tagged, the
person who tagged it, the species size and sex, and information about
the habitat.</p>
<p><em>Points</em> are the simplest vector data type. Each point uses a
single coordinate pair to define its location. It has no area or length
and is specified by two geographic coordinates: latitude and longitude
(or X and Y). Examples of points include addresses, trees, bus stops or
crime incidents.</p>
<p><em>Lines</em> are represented as a connected series of ordered
points that are not enclosed. The ordering of the points is important,
because we need to know which points should be connected. Examples of
lines include roads, rivers, railways, hiking trails, contour lines
(elevation), flight paths, and migration routes.</p>
<p><em>Polygons</em> are represented as a closed shape defined by a
connected sequence of x,y coordinate pairs, where the first and last
coordinate pair are the same and all other pairs are unique. Polygon
should be closed. The start and end point should have the same
coordinates. Examples of polygons include countries, states, parcels of
lands and lakes.</p>
<p>Two R packages that handle vector data are <strong>terra</strong> and
<strong>sf</strong>. Although there are overlaps between the two
packages, and you can convert vector objects represented in one package
into the other, the packages handle vector data in unique ways. We cover
each package below.</p>
<div style="margin-bottom:25px;">

</div>
<div id="terra-package" class="section level3">
<h3><strong>terra package</strong></h3>
<p><br />
</p>
<p>The <strong>terra</strong> package is primarily for creating,
reading, manipulating, and writing raster data. However, it also handles
vector data. In general, the package defines a set of classes to
represent spatial data. These classes represent geometries as well as
attributes (variables) describing the geometries. The main reason for
defining classes is to create a standard representation of a particular
data type to make it easier to write functions (also known as ‘methods’)
for them. The classes start with the name <em>Spat</em>. For vector
data, the relevant class is <em>SpatVector</em>.</p>
<p>To demonstrate how vector data are generally depicted in
<strong>terra</strong>, let’s bring in the polygon shapefile
<em>lux</em>, which is a shapefile of <a
href="https://en.wikipedia.org/wiki/Luxembourg">Luxembourg</a> and is a
part of the <strong>terra</strong> package. The <a
href="https://desktop.arcgis.com/en/arcmap/latest/manage-data/shapefiles/what-is-a-shapefile.htm">shapefile</a>
is the most commonly used file format for vector data. Use the following
code to to get the full path name of the file’s location. We need to do
this as the location of this file depends on where the
<strong>terra</strong> package is installed. You should not use the
<code>system.file()</code> function for your own files. In other words,
don’t dwell too much on what this function is doing. It only serves for
creating examples with data that ships with R.</p>
<pre class="r"><code>filename &lt;- system.file(&quot;ex/lux.shp&quot;, package=&quot;terra&quot;)
filename</code></pre>
<pre><code>## [1] &quot;/Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/library/terra/ex/lux.shp&quot;</code></pre>
<p>Now we have the filename and its path that we need to use. To bring
it into R, use the function <code>vect()</code>, which is a part of the
<strong>terra</strong> package.</p>
<pre class="r"><code>lux &lt;- vect(filename)</code></pre>
<p>We find that it is a <em>SpatVector</em> object.</p>
<pre class="r"><code>class(lux)</code></pre>
<pre><code>## [1] &quot;SpatVector&quot;
## attr(,&quot;package&quot;)
## [1] &quot;terra&quot;</code></pre>
<p>We can use the base <code>plot()</code> function to make a map of
Luxembourg’s regions.</p>
<pre class="r"><code>plot(lux)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-7-1.png" /><!-- --></p>
<p>We mapped just the polygons above, but we can also map one of the
attributes. Here we show a choropleth map (discussed on pages 73-76 in
OSU) of the area of each region <em>AREA</em>.</p>
<pre class="r"><code>plot(lux, &#39;AREA&#39;)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-8-1.png" /><!-- --></p>
<p>Or plot a categorical variable such as the name of each region</p>
<pre class="r"><code>plot(lux, &#39;NAME_2&#39;)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-9-1.png" /><!-- --></p>
<p>We can manipulate the <em>SpatVector</em> like we would a regular
data frame. Here we’ll use base R to manipulate. To extract the
attributes (<em>data.frame</em>) from a Spatial object, use:</p>
<pre class="r"><code>d &lt;- as.data.frame(lux)
head(d)</code></pre>
<pre><code>##   ID_1       NAME_1 ID_2     NAME_2 AREA   POP
## 1    1     Diekirch    1   Clervaux  312 18081
## 2    1     Diekirch    2   Diekirch  218 32543
## 3    1     Diekirch    3    Redange  259 18664
## 4    1     Diekirch    4    Vianden   76  5163
## 5    1     Diekirch    5      Wiltz  263 16735
## 6    2 Grevenmacher    6 Echternach  188 18899</code></pre>
<p>You can extract a variable using the <code>$</code> convention.</p>
<pre class="r"><code>lux$NAME_2</code></pre>
<pre><code>##  [1] &quot;Clervaux&quot;         &quot;Diekirch&quot;         &quot;Redange&quot;          &quot;Vianden&quot;         
##  [5] &quot;Wiltz&quot;            &quot;Echternach&quot;       &quot;Remich&quot;           &quot;Grevenmacher&quot;    
##  [9] &quot;Capellen&quot;         &quot;Esch-sur-Alzette&quot; &quot;Luxembourg&quot;       &quot;Mersch&quot;</code></pre>
<p>Can we use <strong>tidyverse</strong> functions on
<em>SpatVector</em>s?</p>
<pre class="r"><code>lux %&gt;% 
  select(NAME_2)</code></pre>
<pre><code>## Error in `UseMethod()`:
## ! no applicable method for &#39;select&#39; applied to an object of class &quot;SpatVector&quot;</code></pre>
<p>Oh oh. <strong>terra</strong> is not tidy friendly. Hence, why base R
is still important to understand, as some important packages have not
integrated the tidy workflow (although, see the package <a
href="https://cran.case.edu/web/packages/tidyterra/vignettes/tidyterra.html"><strong>tidyterra</strong></a>
as an attempt to bridge this integration gap).</p>
<p>Let’s create a new variable, for example a new variable containing
<em>AREA</em> multiplied by 100</p>
<pre class="r"><code>lux$AREA_100 &lt;- lux$AREA*100</code></pre>
<p>Now, sub-setting by variable.</p>
<pre class="r"><code>lux[, &#39;NAME_2&#39;]</code></pre>
<pre><code>##  class       : SpatVector 
##  geometry    : polygons 
##  dimensions  : 12, 1  (geometries, attributes)
##  extent      : 5.74414, 6.528252, 49.44781, 50.18162  (xmin, xmax, ymin, ymax)
##  source      : lux.shp
##  coord. ref. : lon/lat WGS 84 (EPSG:4326) 
##  names       :   NAME_2
##  type        :    &lt;chr&gt;
##  values      : Clervaux
##                Diekirch
##                 Redange</code></pre>
<p>Note how this code is different from the code above it. Above
<code>lux$NAME_2</code> returns a vector of values is returned. With the
approach directly above you get a new <em>SpatVector</em> with only one
variable.</p>
<p>Selecting rows (records).</p>
<pre class="r"><code>g &lt;- lux[lux$NAME_1 == &#39;Grevenmacher&#39;,]
plot(g)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-15-1.png" /><!-- --></p>
<p>There are other <strong>terra</strong> spatial data functions you can
use to manipulate the polygons. Since we won’t be focusing too much on
the <strong>terra</strong> package for handling vector data in this
class, you can learn more about these functions on your own <a
href="https://rspatial.org/spatial/7-vectmanip.html">here</a>.</p>
<p>Although useful when working with vector data within the
<strong>terra</strong> universe, it is not the current standard package
for processing vector data in R. This designation belongs to the
<strong>sf</strong> package, which was created in 2016. In contrast to
the <strong>terra</strong> package, which uses a rather complex data
structure, <strong>sf</strong> is much easier to use and fits in very
naturally with the <strong>tidyverse</strong>. Which means we can use
most of the functions we went through when we learned about the
<strong>tidyverse</strong> package to clean and process
<strong>sf</strong> spatial objects. This includes mapping vector data
using <strong>ggplot2</strong>, which we will cover later.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="sf-package" class="section level3">
<h3><strong>sf package</strong></h3>
<p><br />
</p>
<p>The <strong>sf</strong> package is the major package for handling
vector data in R. It conceives of spatial objects as
<strong>s</strong>imple <strong>f</strong>eatures. What is a feature? A
feature is thought of as a thing, or an object in the real world, such
as a building or a tree. A wetland preserve can be a feature. As can a
city and a neighborhood. Features have a geometry describing where on
Earth the features are located, and they have attributes, which describe
other properties. The main application of simple feature geometries is
to describe two-dimensional geometries by points, lines, or polygons. To
learn more about simple features, check out <a
href="https://r.geocompx.org/spatial-class#intro-sf">Chapter 2</a> in
GWR.</p>
<div style="margin-bottom:25px;">

</div>
<div id="reading-spatial-data" class="section level4">
<h4><strong>Reading spatial data</strong></h4>
<p><br />
</p>
<p>The function for reading in spatial data into R as an
<strong>sf</strong> object is <code>st_read()</code>. I zipped up and
uploaded onto GitHub a folder containing files for this lab. Set your
working directory to an appropriate folder and use the following code to
download and unzip the file.</p>
<pre class="r"><code>#insert the pathway to the folder you want your data stored into
setwd(&quot;insert your pathway here&quot;)
#downloads file into your working directory 
download.file(url = &quot;https://raw.githubusercontent.com/geo200cn/data/master/spatialsflab.zip&quot;, destfile = &quot;spatialsflab.zip&quot;)
#unzips the zipped file
unzip(zipfile = &quot;spatialsflab.zip&quot;)</code></pre>
<p>You should see the shapefiles <em>saccityinc.shp</em>,
<em>Rivers.shp</em>, <em>Parks.shp</em>, and <em>EV_Chargers.shp</em> in
the folder you specified in <code>setwd()</code>. These files contain
Sacramento city <a
href="https://www2.census.gov/geo/pdfs/education/CensusTracts.pdf">Census
tract</a> polygons, Sacramento river polylines, Sacramento <a
href="https://data.cityofsacramento.org/datasets/b3047674f3f04a759c484fe5208faf6c_0/about">parks</a>
polygons, and <a
href="https://data.cityofsacramento.org/datasets/93efdbcdbc744210848dd7f601e622e3_0/about">Sacramento
Electric Vehicle Charging Locations</a> points, respectively. You should
also see a csv file <em>sacrace.csv</em>, which contains Sacramento city
Census tract race/ethnic population counts. First, read in the
shapefiles using the <strong>sf</strong> function
<code>st_read()</code>.</p>
<pre class="r"><code>saccitytracts &lt;- st_read(&quot;saccityinc.shp&quot;, stringsAsFactors = FALSE)
parks &lt;- st_read(&quot;Parks.shp&quot;, stringsAsFactors = FALSE)
rivers &lt;- st_read(&quot;Rivers.shp&quot;, stringsAsFactors = FALSE)
evcharge &lt;- st_read(&quot;EV_Chargers.shp&quot;, stringsAsFactors = FALSE)</code></pre>
<p>The argument <code>stringsAsFactors = FALSE</code> tells R to keep
any variables that look like a character as a character and not a
factor.</p>
<p>Using <code>class()</code> we find that they are <strong>sf</strong>
objects</p>
<pre class="r"><code>class(saccitytracts)</code></pre>
<pre><code>## [1] &quot;sf&quot;         &quot;data.frame&quot;</code></pre>
<p>Look at <em>saccitytracts</em></p>
<pre class="r"><code>saccitytracts</code></pre>
<pre><code>## Simple feature collection with 122 features and 2 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -121.5601 ymin: 38.43789 xmax: -121.3627 ymax: 38.6856
## Geodetic CRS:  NAD83
## First 10 features:
##         GEOID medinc                       geometry
## 1  6067007104   High MULTIPOLYGON (((-121.5076 3...
## 2  6067000400   High MULTIPOLYGON (((-121.4748 3...
## 3  6067006900    Low MULTIPOLYGON (((-121.4729 3...
## 4  6067003102 Medium MULTIPOLYGON (((-121.4457 3...
## 5  6067006400    Low MULTIPOLYGON (((-121.4291 3...
## 6  6067001101    Low MULTIPOLYGON (((-121.4989 3...
## 7  6067009633 Medium MULTIPOLYGON (((-121.4476 3...
## 8  6067001900 Medium MULTIPOLYGON (((-121.4824 3...
## 9  6067009614   High MULTIPOLYGON (((-121.4447 3...
## 10 6067004906 Medium MULTIPOLYGON (((-121.4531 3...</code></pre>
<p>The output gives us pertinent information regarding the spatial file,
including the type (MULTIPOLYGON), the extent or bounding box, the <a
href="https://www.nceas.ucsb.edu/sites/default/files/2020-04/OverviewCoordinateReferenceSystems.pdf">coordinate
reference system</a>, and the variables in the attribute dataset. Read
<a href="https://r.geocompx.org/spatial-class#crs-intro">Chapter 2</a>
in GWR if you’d like a brief intro on coordinate reference systems. Most
important is the <em>geometry</em> column, which tells you that the
object is in spatial format. Click on <em>saccitytracts</em> in your
environment window. You’ll find that a window pops up in the top left
portion of your interface. Unlike with <em>SpatVector</em> objects, an
<strong>sf</strong> object looks and feels like a regular data frame.
The only difference is there is a <em>geometry</em> column. This column
“spatializes” the dataset, or lets R know where each feature is
geographically located on the Earth’s surface. Check out the other
datasets we brought in and determine how they differ from one
another.</p>
<p>You can bring in other types of spatial data files other than
shapefiles. See a list of these file types <a
href="https://cran.r-project.org/web/packages/sf/vignettes/sf2.html">here</a>.</p>
<p>Next bring in <em>sacrace.csv</em> which contains Hispanic
(<em>hisp</em>), non-Hispanic Asian (<em>nhasn</em>), non-Hispanic Black
(<em>nhblk</em>), non-Hispanic white (<em>nhwhite</em>) and total
population (<em>tpopr</em>) for tracts in Sacramento city. Use the
function <code>read_csv()</code>.</p>
<pre class="r"><code>sacrace &lt;- read_csv(&quot;sacrace.csv&quot;)</code></pre>
<p>The function for saving or writing <strong>sf</strong> objects onto
your hard drive is <code>st_write()</code>.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="data-transformation" class="section level4">
<h4><strong>Data transformation</strong></h4>
<p><br />
</p>
<p><strong>sf</strong> objects are data frames. This means that they are
tidy friendly. You can use many of the functions we learned <a
href="https://geo200cn.github.io/data_transformation.html">previously</a>
to manipulate <strong>sf</strong> objects, and this includes our new
best friend the pipe <code>%&gt;%</code> operator. For example, let’s do
the following tasks on <em>saccitytracts</em>.</p>
<ol style="list-style-type: decimal">
<li>Merge in the race/ethnicity and total population variables from
<em>sacrace</em> into <em>saccitytracts</em> using
<code>left_join()</code>. The common ID is <em>GEOID</em></li>
<li>Create the variable <em>pwh</em> which is the percent of the tract
population that is non-Hispanic white using <code>mutate()</code></li>
<li>Keep just the variables <em>GEOID</em>, <em>medinc</em>, and
<em>pwh</em> using the function <code>select()</code></li>
</ol>
<p>We do this in one line of continuous code using the pipe operator
<code>%&gt;%</code></p>
<pre class="r"><code>saccitytracts &lt;- saccitytracts %&gt;%
            left_join(sacrace, by = &quot;GEOID&quot;) %&gt;%
            mutate(pwh = nhwhite/tpopr) %&gt;%
            select(GEOID, medinc, pwh)</code></pre>
<p>You can also keep certain polygons (i.e. subset rows). For example,
keep the tracts that are majority non-white</p>
<pre class="r"><code>mwhite &lt;- saccitytracts %&gt;%
          filter(pwh &lt; 0.5)
#number of neighborhoods in Sacramento that are majority non white
nrow(mwhite)</code></pre>
<pre><code>## [1] 94</code></pre>
<p>The main takeaway: <strong>sf</strong> objects are tidy friendly, so
you can use many of the tidy functions on these objects to manipulate
your data set.</p>
<p>While <strong>tidyverse</strong> offers a set of functions for data
manipulation, the <strong>sf</strong> package offers a suite of
functions unique to manipulating spatial data. Spatial data manipulation
involves cleaning or altering your data set based on the geographic
location of features. Most of these functions start out with the prefix
<code>st_</code>.</p>
<p>Common functions to manipulate <strong>sf</strong> objects include
the following:</p>
<ul>
<li><code>st_read()</code> reads a <strong>sf</strong> object,</li>
<li><code>st_write()</code> writes a <strong>sf</strong> object,</li>
<li><code>st_crs()</code> gets or sets a new coordinate reference system
(CRS),</li>
<li><code>st_transform()</code> transforms data to a new CRS,</li>
<li><code>st_intersection()</code> intersects <strong>sf</strong>
objects,</li>
<li><code>st_union()</code> combines several <strong>sf</strong> objects
into one,</li>
<li><code>st_simplify()</code> simplifies a <strong>sf</strong>
object,</li>
<li><code>st_coordinates()</code> retrieves coordinates of a
<strong>sf</strong> object,</li>
<li><code>st_as_sf()</code> converts a foreign object to a
<strong>sf</strong> object.</li>
</ul>
<p>To see all of the functions, type in</p>
<pre class="r"><code>methods(class = &quot;sf&quot;)</code></pre>
<p>We won’t go through these functions as the list is quite extensive.
You can learn about them in GWR’s excellent <a
href="https://geocompr.robinlovelace.net/spatial-operations.html">guide</a>.
The focus of this lab is to learn how to map <strong>sf</strong>
objects, which we’ll get to later in this guide.</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
</div>
<div id="raster-data" class="section level2">
<h2><strong>Raster data</strong></h2>
<p><br />
</p>
<p>Raster data is commonly used to represent spatially continuous
phenomena such as elevation. A raster divides the world into a grid of
equally sized rectangles (referred to as cells or, in the context of
satellite remote sensing, pixels) that all have one or more values (or
missing values) for the variables of interest. A raster cell value
should normally represent the average (or majority) value for the area
it covers. However, in some cases the values are actually estimates for
the center of the cell (in essence becoming a regular set of points with
an attribute). We will focus on regular grids in this class, but know
that several other types of grids exist, including rotated, sheared,
rectilinear, and curvilinear grids (see <a
href="https://r-spatial.org/book/01-hello.html#raster-types">chapter
1</a> of Pebesma and Bivand (2023b)).</p>
<p>In contrast to vector data, in raster data the geometry is not
explicitly stored as coordinates. It is implicitly set by knowing the
spatial extent and the number of rows and columns in which the area is
divided. From the extent and number of rows and columns, the size of the
raster cells (spatial resolution) can be computed. While raster cells
can be thought of as a set of regular polygons, it would be very
inefficient to represent the data that way as coordinates for each cell
would have to be stored explicitly. It would also dramatically increase
processing speed in most cases. Also in contrast to vector data, the
cell of one raster layer can only hold a single value. The value might
be continuous or categorical.</p>
<p>The main package for handling raster data in R is
<strong>terra</strong>. The package is built around a number of
“classes” of which the <em>SpatVector</em> we already met earlier. The
raster class is <em>SpatRaster</em>, which we introduce next.</p>
<div style="margin-bottom:25px;">

</div>
<div id="spatraster" class="section level3">
<h3><strong>SpatRaster</strong></h3>
<p><br />
</p>
<p>A <em>SpatRaster</em> represents multi-layer (multi-variable) raster
data. A <em>SpatRaster</em> always stores a number of fundamental
parameters describing its geometry. These include the number of columns
and rows, the spatial extent, and the Coordinate Reference System. In
addition, a <em>SpatRaster</em> can store information about the file in
which the raster cell values are stored. Or, if there is no such a file,
a <em>SpatRaster</em> can hold the cell values in memory.</p>
<p>A <em>SpatRaster</em> can easily be created from scratch using the
function <code>rast()</code>. The default settings will create a global
raster data structure with a longitude/latitude coordinate reference
system and 1 by 1 degree cells. You can change these settings by
providing additional arguments such as <em>xmin</em>, <em>nrow</em>,
<em>ncol</em>, and/or <em>crs</em>, to the function. You can also change
these parameters after creating the object. If you set the projection,
this is only to properly define it, not to change it. To transform a
<em>SpatRaster</em> to another coordinate reference system
(reprojection) you can use the function <code>warp()</code>. To learn
more about reprojection, check out <a
href="https://r.geocompx.org/reproj-geo-data">Chapter 7</a> in GWR. But
note that in most cases where real data is analyzed, these objects are
created from a file.</p>
<p>Let’s start by creating a <em>SpatRaster</em> from scratch using the
<code>rast()</code> function.</p>
<pre class="r"><code>r &lt;- rast(ncol=10, nrow=10, xmin=-150, xmax=-80, ymin=20, ymax=60)
r</code></pre>
<pre><code>## class       : SpatRaster 
## size        : 10, 10, 1  (nrow, ncol, nlyr)
## resolution  : 7, 4  (x, y)
## extent      : -150, -80, 20, 60  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84)</code></pre>
<p>Dedicated functions report each component: <code>dim()</code> returns
the number of rows <em>nrow</em>, columns <em>ncol</em> and layers
<em>nlyr</em>; <code>ncell()</code> the number of cells (pixels);
<code>res()</code> the spatial resolution; <code>ext()</code> its
spatial extent; and <code>crs()</code> its coordinate reference
system.</p>
<p><em>SpatRaster</em> <em>r</em> only has the geometry of a raster data
set. That is, it knows about its location, resolution, etc., but there
are no values associated with it. We check this using the function
<code>hasValues()</code>.</p>
<pre class="r"><code>hasValues(r)</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>Let’s assign some values. In this case we assign a vector of random
numbers with a length that is equal to the number of raster cells in
<em>r</em> using the function <code>runif()</code>.</p>
<pre class="r"><code>values(r) &lt;- runif(ncell(r))
r</code></pre>
<pre><code>## class       : SpatRaster 
## size        : 10, 10, 1  (nrow, ncol, nlyr)
## resolution  : 7, 4  (x, y)
## extent      : -150, -80, 20, 60  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84) 
## source(s)   : memory
## name        :       lyr.1 
## min value   : 0.005674657 
## max value   : 0.935946088</code></pre>
<p>The raster layer is provided under <em>name</em>. You could also
assign cell numbers (in this case overwriting the previous values)</p>
<pre class="r"><code>values(r) &lt;- 1:ncell(r)
r</code></pre>
<pre><code>## class       : SpatRaster 
## size        : 10, 10, 1  (nrow, ncol, nlyr)
## resolution  : 7, 4  (x, y)
## extent      : -150, -80, 20, 60  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84) 
## source(s)   : memory
## name        : lyr.1 
## min value   :     1 
## max value   :   100</code></pre>
<p>We can plot this raster object and its values using base
<code>plot()</code>.</p>
<pre class="r"><code>plot(r)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-29-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="reading-in-raster-data" class="section level3">
<h3><strong>Reading in raster data</strong></h3>
<p><br />
</p>
<p>In most applications you will bring in a raster dataset directly from
a file. The <strong>terra</strong> package can use raster files in
several formats. Supported formats for reading include GeoTIFF, ESRI,
ENVI, and ERDAS. Most formats supported for reading can also be written
to.</p>
<p>Here is an example using the <em>elev.tif</em> dataset (taken from
the <strong>terra</strong> package). Use the following code to bring in
the data. The file provides elevation values for Luxembourg. As noted
earlier, do not use this <code>system.file</code> construction for your
own files.</p>
<pre class="r"><code>filename &lt;- system.file(&quot;ex/elev.tif&quot;, package=&quot;terra&quot;)</code></pre>
<p>Now bring in the file using the function <code>rast()</code>.</p>
<pre class="r"><code>elev &lt;- rast(filename)
elev</code></pre>
<pre><code>## class       : SpatRaster 
## size        : 90, 95, 1  (nrow, ncol, nlyr)
## resolution  : 0.008333333, 0.008333333  (x, y)
## extent      : 5.741667, 6.533333, 49.44167, 50.19167  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (EPSG:4326) 
## source      : elev.tif 
## name        : elevation 
## min value   :       141 
## max value   :       547</code></pre>
<p>We see that this data is a <em>SpatRaster</em>. Remember that raster
data are basically grid data, and the grid we have contains 90 rows, 95
columns, 8550 (90 x 95) cells. There’s also just 1 layer (elevation),
and the min and max values are 141 and 547, respectively. Note that
raster objects may have more than one layer of data values (e.g.,
<em>elev</em> could also include the layers temperature and humidity).
Let’s plot what we got (elevation values) using <code>plot()</code>.</p>
<pre class="r"><code>plot(elev)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-32-1.png" /><!-- --></p>
<p>The function for saving or writing raster data onto your hard drive
is <code>writeRaster()</code>.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="raster-operations" class="section level3">
<h3><strong>Raster operations</strong></h3>
<p><br />
</p>
<p>Similar to vector data, you can manipulate raster data, such as
assign values to cells, add two rasters, and so on. There are generally
four types of raster operations.</p>
<ol style="list-style-type: decimal">
<li><strong>Local: Each output cell value is computed using only the
corresponding input cell(s) at the same location.</strong></li>
</ol>
<p>Most algebraic operations can be applied to rasters as they would
with any vector element. You can transform cell values directly. For
example, you can add the value one to each cell in the raster
<em>r</em>.</p>
<pre class="r"><code>r &lt;- r+1</code></pre>
<p>You can also add, subtract, multiply etc. two or more layers of the
same dimension. For example, we can create a new layer <em>r2</em> that
multiplies the cell values of <em>r</em> by each other.</p>
<pre class="r"><code>r2 &lt;- r * r</code></pre>
<p>Another local operation that can be applied to a raster is
reclassification. In the following example, we will assign all r values
that are less than 50 a 1 and otherwise a 0. A simple way to do this is
to apply a conditional statement.</p>
<pre class="r"><code>r4 &lt;- r &lt; 50</code></pre>
<p>Plot to see if we got what we wanted.</p>
<pre class="r"><code>plot(r4)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-36-1.png" /><!-- --></p>
<p>Note that all 0 pixels are coded as FALSE and all 1 pixels are coded
as TRUE. You can also use the <strong>terra</strong> function
<code>ifel()</code> to assign a value to a cell if it meets a condition
or not.</p>
<ol start="2" style="list-style-type: decimal">
<li><strong>Focal: Each output cell value is computed using a
neighborhood of surrounding cells (a moving window).</strong></li>
</ol>
<p>Operations or functions applied focally to rasters involve user
defined neighboring cells. Focal operations can be performed using the
<code>focal()</code> function. For example, to smooth out the elevation
raster by computing the mean cell values over a 11 by 11 cells window,
type:</p>
<pre class="r"><code>elev3 &lt;- focal(elev, w = 11, 
               fun = mean, 
               expand = TRUE)

plot(elev3)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-37-1.png" /><!-- --></p>
<p>Here, for each cell, you are taking the mean of that cell’s elevation
and the elevation values of the 120 cells surrounding it
(<code>w = 11</code> means an 11 by 11 window).</p>
<ol start="3" style="list-style-type: decimal">
<li><strong>Zonal: Output values are computed for zones (groups of
cells) defined by another raster or vector layer.</strong></li>
</ol>
<p>Zonal operations often involve two layers, one with the values to be
aggregated (raster), the other with the defined zones (polygons or
vector data). Here, you are interested in obtaining a summary statistic
of raster values (e.g. mean, maximum, standard deviation, etc.) within
each polygon. The <code>extract()</code> function allows you to do this.
The function requires a <em>SpatRaster</em> object and either a
<em>SpatVector</em> or <em>sf</em> object. You’ll get practice with this
zonal operation in this week’s assignment.</p>
<ol start="4" style="list-style-type: decimal">
<li><strong>Global: Computes a statistic using all cells in the raster
at once, returning a single value.</strong></li>
</ol>
<p>The main global function in <strong>terra</strong> is
<code>global()</code>. What is the mean value of all cells in the raster
<em>r</em>?</p>
<pre class="r"><code>global(r, fun = &quot;mean&quot;, na.rm = TRUE)</code></pre>
<pre><code>##       mean
## lyr.1 51.5</code></pre>
<p>We won’t go through all of the possible operations in this guide. You
will have an opportunity to explore them in your assignment this week.
You can also learn more about functions that manipulate rasters <a
href="https://rspatial.org/spatial/8-rastermanip.html">here</a>.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="vector-to-raster-conversion" class="section level3">
<h3><strong>Vector to raster conversion</strong></h3>
<p><br />
</p>
<p>Rather than bringing in a raster dataset, you often have to convert a
vector object, typically polygons or points, into a raster. Polygon to
raster conversion is typically done to create a <em>SpatRaster</em> that
can act as a mask, i.e. to set to NA a set of cells of a raster object,
or to summarize values on a raster by zone. For example a country
polygon is transferred to a raster that is then used to set all the
cells outside that country to NA; whereas polygons representing
administrative regions such as states can be transferred to a raster to
summarize raster values by region.</p>
<p>Let’s turn the Luxembourg polygon <em>lux</em> we used earlier into a
raster. In order to change it into a raster object, use the function
<code>rast()</code>, and designate the raster grid (number of
cells).</p>
<pre class="r"><code>r &lt;- rast(lux, ncols=75, nrows=100 )</code></pre>
<p>The size of each pixel or cell in the raster grid is defined by the
number of columns <code>ncols</code> and rows <code>nrows</code>. You
can also defines the resolution using the <code>res</code> argument.</p>
<p>Plor <em>r</em></p>
<pre class="r"><code>plot(r)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-40-1.png" /><!-- --></p>
<p>You should get a blank map. Object <em>r</em> only has the skeleton
of a raster data set. That is, the object <em>r</em> created only
consists of the raster geometry, that is, we have defined the number of
rows and columns, and where the raster is located in geographic space,
but there are no cell-values associated with it. The function
<code>rasterize()</code>transfers values associated with ‘object’ type
spatial data (points, lines, polygons) to raster cells. Let’s transfer
the area <em>AREA</em> from <em>lux</em> to their associated raster cell
in <em>r</em>.</p>
<pre class="r"><code>vr &lt;- rasterize(lux, r, &#39;AREA&#39;)
plot(vr)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-41-1.png" /><!-- --></p>
<p>Notice the difference between how this map “looks” compared to the
vector data mapped earlier. Why is there a difference?</p>
<p>Point to raster conversion is often done with the purpose to analyze
the point data. For example to count the number of distinct species
(represented by point observations) that occur in each raster cell.
<code>rasterize()</code> takes a <em>SpatRaster</em> object to set the
spatial extent and resolution, and a function to determine how to
summarize the points (or an attribute of each point) by cell.</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="mapping" class="section level2">
<h2><strong>Mapping</strong></h2>
<p><br />
</p>
<p>Now that you’ve learned the basics of bringing in and manipulating
spatial data, let’s go through how we can map it. We already created
some maps above, but let’s go through the set of map types discussed in
OSU Ch. 3. We will cover two ways of mapping <strong>sf</strong>
objects: <code>ggplot()</code> from the <strong>ggplot2</strong> package
and <code>tm_shape()</code> from the <strong>tmap</strong> package.
These are not the only packages that provide mapping functions. We
already used the function <code>plot()</code> from the
<strong>base</strong> package to create a few simple maps above. But the
<strong>tmap</strong> and <strong>ggplot2</strong> packages are the most
flexible and most used mapping packages in R. See <a
href="https://r.geocompx.org/adv-map.html?q=brewer#other-mapping-packages">Chapter
9.6</a> in GWR for a description of other available mapping
packages.</p>
<div style="margin-bottom:25px;">

</div>
<div id="ggplot" class="section level3">
<h3><strong>ggplot</strong></h3>
<p><br />
</p>
<p>Because <strong>sf</strong> is tidy friendly, it is no surprise we
can use the tidyverse plotting function <code>ggplot()</code> to make
maps. We already received an introduction to <code>ggplot()</code> a <a
href="https://geo200cn.github.io/eda.html#Data_visualization">few labs
ago</a>. Recall its basic structure:</p>
<p><br></p>
<pre><code>ggplot(data = &lt;DATA&gt;) +
      &lt;GEOM_FUNCTION&gt;(mapping = aes(x, y)) +
      &lt;OPTIONS&gt;()</code></pre>
<p><br></p>
<p>In mapping, <code>geom_sf()</code> is
<code>&lt;GEOM_FUNCTION&gt;()</code>. Unlike with functions like
<code>geom_histogram()</code> and <code>geom_boxplot()</code>, we don’t
specify an x and y axis. Instead you use fill if you want to map a
variable or color to just map boundaries.</p>
<p>Let’s use <code>ggplot()</code> to make a choropleth map. Choropleth
maps are discussed on page 73-76 in OSU. We need to specify a numeric
variable in the <code>fill =</code> argument within
<code>geom_sf()</code>. Here we map percent non-Hispanic white
<em>pwh</em>.</p>
<pre class="r"><code>ggplot(data = saccitytracts) +
  geom_sf(aes(fill = pwh))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-42-1.png" /><!-- --></p>
<p>We can also specify a title (as well as subtitles and captions) using
the <code>labs()</code> function.</p>
<pre class="r"><code>ggplot(data = saccitytracts) +
  geom_sf(aes(fill = pwh)) +
    labs(title = &quot;Percent white Sacramento City Tracts&quot;)  </code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-43-1.png" /><!-- --></p>
<p>The package <strong>ggspatial</strong> enhances
<strong>ggplot2</strong>’s mapping capabilities by providing additional
options. For example, we can add a north arrow to the map using the
function <code>annotation_north_arrow()</code>.</p>
<pre class="r"><code>ggplot(data = saccitytracts) +
  geom_sf(aes(fill = pwh)) +
  annotation_north_arrow(height = unit(0.75, &quot;cm&quot;),
                         width = unit(0.75, &quot;cm&quot;)) +
  labs(title = &quot;Percent white Sacramento City Tracts&quot;)  </code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-44-1.png" /><!-- --></p>
<p>And a scale bar using <code>annotation_scale()</code>, where
<code>location =</code> indicates where to put the scale bar (“br” is
bottom right). Scale bars provide a visual indication of the size of
features, and distance between features, on the map.</p>
<pre class="r"><code>ggplot(data = saccitytracts) +
  geom_sf(aes(fill = pwh)) +
  annotation_north_arrow(height = unit(0.75, &quot;cm&quot;),
                         width = unit(0.75, &quot;cm&quot;)) +
  annotation_scale(location = &quot;br&quot;,
                   height = unit(0.1, &quot;cm&quot;)) +
  labs(title = &quot;Percent white Sacramento City Tracts&quot;)  </code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-45-1.png" /><!-- --></p>
<p>We can make further layout adjustments to the map. Don’t like a blue
scale on the legend? You can change it using the
<code>scale_file_gradient()</code> function. Let’s change it to a white
to red gradient. We can also eliminate the gray tract border colors to
make the fill color distinction clearer. We do this by specifying
<code>color = NA</code> inside <code>geom_sf()</code>. We can also get
rid of the gray background by specifying a basic black and white theme
using <code>theme_bw()</code>.</p>
<pre class="r"><code>ggplot(data = saccitytracts) +
  geom_sf(aes(fill = pwh), color = NA) +
  scale_fill_gradient(low= &quot;white&quot;, high = &quot;red&quot;, na.value =&quot;gray&quot;) +  
    annotation_north_arrow(height = unit(0.75, &quot;cm&quot;),
                         width = unit(0.75, &quot;cm&quot;)) +
  annotation_scale(location = &quot;br&quot;,
                   height = unit(0.1, &quot;cm&quot;)) +
  labs(title = &quot;Percent white Sacramento City Tracts&quot;,
       caption = &quot;Source: American Community Survey&quot;) +  
  theme_bw()</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-46-1.png" /><!-- --></p>
<p>I also added a caption indicating the source of the data using the
<code>captions =</code> parameter within <code>labs()</code>.</p>
<p>You also use <code>geom_sf()</code> for mapping points (an example of
a pin map as described in OSU page 66). Color them black using
<code>fill = "black"</code>. Let’s map the location of EV chargers in
Sacramento.</p>
<pre class="r"><code>ggplot(data = evcharge) +
  geom_sf(fill = &quot;black&quot;) +
  labs(title = &quot;EV Charge Stations Sacramento City Tracts&quot;,
       caption = &quot;Source: City of Sacramento&quot;) +  
  theme_bw()</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-47-1.png" /><!-- --></p>
<p>You can overlay the points over Sacramento tracts to give the
locations some perspective. Here, you add two <code>geom_sf()</code> for
the tracts and the EV charge stations.</p>
<pre class="r"><code>ggplot() +
  geom_sf(data = saccitytracts) +
  geom_sf(data = evcharge, fill = &quot;black&quot;) +
  labs(title = &quot;EV Charge Stations Sacramento City Tracts&quot;,
       caption = &quot;Source: City of Sacramento&quot;) +  
  theme_bw()</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-48-1.png" /><!-- --></p>
<p>Note that <code>data =</code> moves out of <code>ggplot()</code> and
into <code>geom_sf()</code> because we are mapping more than one spatial
feature.</p>
<p>What about a map of lines? Here is a map of rivers intersecting with
Sacramento City.</p>
<pre class="r"><code>ggplot() +
  geom_sf(data = rivers, col = &quot;blue&quot;) +
  labs(title = &quot;Sacramento Rivers&quot;,
       caption = &quot;Source: Sacramento County&quot;) +  
  theme_bw()</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-49-1.png" /><!-- --></p>
<p>We can use <code>ggplot()</code> to also map raster data. Here, we
plot the raster data set <em>elev</em> we brought in earlier, which
represents elevation in Luxembourg. To create a map of raster data using
<strong>ggplot2</strong>, we need to transform the data to a data frame
and pass it to <code>geom_raster()</code>. Let’s also plot the
Luxembourg border by creating an <strong>sf</strong> object using
<code>st_as_sf()</code>.</p>
<pre class="r"><code># Transform data to sf object
luxelev &lt;- st_as_sf(as.data.frame(elev, xy = TRUE), coords = c(&quot;x&quot;, &quot;y&quot;))
# Assign CRS
st_crs(luxelev) &lt;- 4326
# Plot
ggplot(luxelev) + 
  geom_sf() +
  geom_raster(data = as.data.frame(elev, xy = TRUE),
              aes(x = x, y = y, fill = elevation))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-50-1.png" /><!-- --></p>
<p>Within <code>aes()</code> you specify the x and y coordinates of the
grid points.</p>
<p>Good additional <strong>ggplot2</strong> resources can be found in
the open source <strong>ggplot2</strong> book (Wickham 2016) and in the
descriptions of the multitude of ‘ggpackages’ such as
<strong>ggrepel</strong> and <strong>tidygraph</strong>.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="tmap" class="section level3">
<h3><strong>tmap</strong></h3>
<p><br />
</p>
<p>Whether one uses the <strong>tmap</strong> or
<strong>ggplot2</strong> is a matter of taste, but I find that
<strong>tmap</strong> has some benefits, so let’s focus on its mapping
functions next.</p>
<strong>tmap</strong> uses the same layered logic as
<strong>ggplot2</strong>. The initial command is
<code>tm_shape()</code>, which specifies the geography to which the
mapping is applied. This is followed by a number of tm_* options that
select the type of map and several optional customizations. Check the
full list of <code>tm_</code> elements <a
href="https://www.rdocumentation.org/packages/tmap/versions/2.0/topics/tmap-element">here</a>.
<div style="margin-bottom:25px;">

</div>
<div id="choropleth-map" class="section level4">
<h4><strong>Choropleth map</strong></h4>
<p><br />
</p>
<p>Let’s make a choropleth map of percent white in Sacramento.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-51-1.png" /><!-- --></p>
<p>You first put the dataset <em>saccitytracts</em> inside
<code>tm_shape()</code>. Because you are plotting polygons, you use
<code>tm_polygons()</code> next. If you are plotting points, you will
use <code>tm_dots()</code>. If you are plotting lines, you will use
<code>tm_lines()</code>. The argument <code>fill = "pwh"</code> tells R
to shade the tracts by the variable <em>pwh</em>.</p>
<p>OSU discusses the importance of breaks and classifications on page
75. <strong>tmap</strong> allows users to specify the classification
style with the <code>fill.scale =</code> argument within
<code>tm_polygons()</code>. For this argument you will need to specify
the <code>style =</code> within <code>tm_scale()</code>. The default
setting uses ‘pretty’ breaks, which rounds breaks into whole numbers
where possible and spaces them evenly. Let’s use
<code>style = "quantile"</code>, which tells R to break up the shading
into quantiles, or equal groups of 5. I find that this is where
<strong>tmap</strong> offers a distinct advantage over
<strong>ggplot2</strong> in that users have greater control over the
legend and bin breaks.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-52-1.png" /><!-- --></p>
<p>You can also change the number of breaks by setting <code>n=</code>.
The default is <code>n=5</code>. Rather than quintiles, you can show
quartiles using <code>n=4</code></p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    n = 4))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-53-1.png" /><!-- --></p>
<p>The argument <code>breaks =</code> allows you to manually set the
breaks.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(breaks = c(0, 0.20, 0.4, 0.6, 0.8, 1.0)))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-54-1.png" /><!-- --></p>
<p>Check out <a href="https://r.geocompx.org/adv-map#scales">this
breakdown</a> of the available classification styles in
<strong>tmap</strong>.</p>
<p>You can overlay multiple features on one map. For example, we can add
park polygons on top of city tracts, providing a visual association
between parks and percent white. You will need to add two
<code>tm_shape()</code> functions each for <em>saccitytracts</em> and
<em>parks</em>.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    n = 4)) +
  tm_shape(parks) +
    tm_polygons(fill = &quot;green&quot;)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-55-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="color-scheme" class="section level4">
<h4><strong>Color scheme</strong></h4>
<p><br />
</p>
<p>Not into the blue shading? The argument <code>values =</code> within
<code>tm_scale()</code> defines the color ranges associated with the
bins and determined by the <code>style</code> arguments. Several
built-in color palettes are contained in <strong>tmap</strong>. There
are three main groups of color palettes: categorical, sequential and
diverging, and each of them serves a different purpose. The first group
is sequential palettes. These follow a gradient, for example from light
to dark colors (light colors often tend to represent lower values), and
are appropriate for continuous (numeric) variables. Below we use the
color scheme “reds” using <code>value = "reds"</code>.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    n = 4,
                                    values = &quot;reds&quot;))</code></pre>
<pre><code>## Multiple palettes called &quot;reds&quot; found: &quot;brewer.reds&quot;, &quot;matplotlib.reds&quot;. The first one, &quot;brewer.reds&quot;, is returned.</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-56-1.png" /><!-- --></p>
<p>Note the message. Under the hood, <code>“reds”</code> refers to one
of the color schemes supported by the <strong>RColorBrewer</strong>
package (see below).</p>
<p>The second group, diverging palettes, typically range between three
distinct colors and are usually created by joining two single-color
sequential palettes with the darker colors at each end. Their main
purpose is to visualize the difference from an important reference
point. For instance, if we used <code>c(“red”, “blue”)</code>, the color
spectrum would move from red to purple, then to blue, with in between
shades. In our example:</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = c(&quot;red&quot;,&quot;blue&quot;)))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-57-1.png" /><!-- --></p>
<p>In order to capture a clearer diverging scale, we insert “white” in
between red and blue.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = c(&quot;red&quot;,&quot;white&quot;, &quot;blue&quot;)))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-58-1.png" /><!-- --></p>
<p>A preferred approach to select a color palette is to chose one of the
schemes contained in the <strong>RColorBrewer</strong> package. These
are based on the research of cartographer Cynthia Brewer (see the
colorbrewer2 <a
href="https://colorbrewer2.org/#type=sequential&amp;scheme=BuGn&amp;n=3">web
site</a> for details). ColorBrewer makes a distinction between
sequential scales (for a scale that goes from low to high), diverging
scales (to highlight how values differ from a central tendency), and
qualitative scales (for categorical variables). For each scale, a series
of single hue and multi-hue scales are suggested. In the
<strong>RColorBrewer</strong> package, these are referred to by a name
(e.g., the “brewer.reds” palette we used above is an example). The full
list is contained in the <strong>RColorBrewer</strong> <a
href="https://www.rdocumentation.org/packages/RColorBrewer/versions/1.1-2/topics/RColorBrewer">documentation</a>.
You should have noticed from the messages produced from the mapping
above that the default “reds” palette is from RColorBrewer. You can
avoid seeing this message in the future by specifying “brewer.reds” for
<code>values =</code>.</p>
<p>There are two very useful commands in this package. One sets a color
palette by specifying its name and the number of desired categories. The
result is a character vector with the hex codes of the corresponding
colors.</p>
<p>For example, we select a sequential color scheme going from blue to
green, as <em>BuGn</em>, by means of the command
<code>brewer.pal</code>, with the number of categories (6) and the
scheme as arguments. The resulting vector contains the HEX codes for the
colors.</p>
<pre class="r"><code>pal &lt;- brewer.pal(6,&quot;BuGn&quot;)
pal</code></pre>
<pre><code>## [1] &quot;#EDF8FB&quot; &quot;#CCECE6&quot; &quot;#99D8C9&quot; &quot;#66C2A4&quot; &quot;#2CA25F&quot; &quot;#006D2C&quot;</code></pre>
<p>The command <code>display.brewer.pal()</code> allows us to explore
different color schemes before applying them to a map. For example:</p>
<pre class="r"><code>display.brewer.pal(6,&quot;BuGn&quot;)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-60-1.png" /><!-- --></p>
<p>Using this palette in our map yields the following result.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = pal))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-61-1.png" /><!-- --></p>
<p>The third group, categorical patterns, will be covered later when we
discuss color patch maps. See <a
href="https://r.geocompx.org/adv-map#scales">Ch. 9.2.4</a> in GWR for a
fuller discussion on color and other schemes you can specify.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="legend" class="section level4">
<h4><strong>Legend</strong></h4>
<p><br />
</p>
<p>There are many options to change the formatting of the legend. Use
the <code>tm_legend()</code> function within <code>tm_polygons()</code>
to change its title, position, orientation, or even disable it. Often,
the automatic title for the legend is not intuitive, since it is simply
the variable name (in our case, <em>pwh</em>). This can be customized by
setting the <code>title =</code> argument within the
<code>tm_legend()</code> function.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = &quot;reds&quot;),
              fill.legend = tm_legend(title = &quot;Percent white&quot;))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-62-1.png" /><!-- --></p>
<p>Another important aspect of the legend is its positioning. This is
handled through the <code>position =</code> argument within
<code>tm_legend()</code>. The default is to position the legend outside
of the map frame at the top right. Often, this default solution is
appropriate, but sometimes further control is needed. We can move the
legend outside or inside the mapping frame using the functions
<code>tm_pos_out()</code>, which keeps the legend outside of the map
frame and <code>tm_pos_in(),</code> which keeps it inside. Within each
of these functions, you specify two values that represent the horizontal
position (“left”, “center”, or “right”), and the vertical position
(“bottom”, “center”, or “top”). For example, to move the legend to the
bottom right in the inside of the map frame:</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = &quot;reds&quot;),
              fill.legend = tm_legend(title = &quot;Percent white&quot;,
                            position = tm_pos_in(&quot;right&quot;, &quot;bottom&quot;)))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-63-1.png" /><!-- --></p>
<p>The legend is too big to fit inside the frame without obscuring some
of the map. There are a number of ways to adjust this, but one method is
to adjust the overall scale of the map. This will automatically adjust
the legend. To adjust the scale, you will need to use the argument
<code>scale =</code> within the function <code>tm_layout()</code>, which
is added after the <code>tm_polygons()</code> function, and allows you
to adjust the overall features of a map. The default scale is 1. When
you reduce the scale below 1, the legend shrinks relative to the size of
the map. Let’s reduce it by 0.6, or 40%.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = &quot;reds&quot;),
              fill.legend = tm_legend(title = &quot;Percent white&quot;,
                            position = tm_pos_in(&quot;right&quot;, &quot;bottom&quot;))) +
    tm_layout(scale = 0.6)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-64-1.png" /><!-- --></p>
<p>There is also the option to position the legend outside the frame of
the map. This is accomplished by setting
<code>position = tm_pos_out()</code> as such.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = &quot;reds&quot;),
              fill.legend = tm_legend(title = &quot;Percent white&quot;,
                            position = tm_pos_out(&quot;right&quot;, &quot;center&quot;))) +
    tm_layout(scale = 0.6)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-65-1.png" /><!-- --></p>
<p>We can also customize the background color of the legend, its
alignment, font, etc. The <code>tm_legend()</code> function has a vast
number of options, as detailed in the <a
href="https://r-tmap.github.io/tmap/reference/tm_legend.html">documentation</a>.
Also check <a href="https://r.geocompx.org/adv-map#legends">Ch.
9.2.5</a> in GWR and the official tmap <a href="">website</a> for more
examples.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="title" class="section level4">
<h4><strong>Title</strong></h4>
<p><br />
</p>
<p>An important feature that you typically include in a map is the
title. We can set the title of the map using the function
<code>tm_title()</code>.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = &quot;reds&quot;),
              fill.legend = tm_legend(title = &quot;Percent white&quot;,
                            position = tm_pos_out(&quot;right&quot;, &quot;center&quot;))) +
    tm_title(&quot;Percent white Sacramento tracts&quot;) +
    tm_layout(scale = 0.6)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-66-1.png" /><!-- --></p>
<p>The default position of the title is at the center outside of the
frame. Similar to the legend, you can position the title using the
<code>position =</code> argument and the functions
<code>tm_pos_in()</code> and <code>tm_pos_out()</code>. For example, the
following code moves the the title inside the frame, and positions it
center and right:</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = &quot;reds&quot;),
              fill.legend = tm_legend(title = &quot;Percent white&quot;,
                            position = tm_pos_out(&quot;right&quot;, &quot;center&quot;))) +
    tm_title(&quot;Percent white Sacramento tracts&quot;,
                        position = tm_pos_in(&quot;center&quot;, &quot;top&quot;)) +
    tm_layout(scale = 0.6)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-67-1.png" /><!-- --></p>
<p>Not good, so we’ll keep it outside.</p>
<p>There are many arguments within <code>tm_title()</code> that will
allow you to change the font type, color, size and other features of the
title.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="other-features" class="section level4">
<h4><strong>Other features</strong></h4>
<p><br />
</p>
<p>We need to add other key elements to the map. First, the scale bar,
which you can add using the function <code>tm_scalebar()</code>.</p>
<pre class="r"><code>tm_shape(saccitytracts, unit = &quot;mi&quot;) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = &quot;reds&quot;),
              fill.legend = tm_legend(title = &quot;Percent white&quot;,
                            position = tm_pos_out(&quot;right&quot;, &quot;center&quot;))) +
    tm_scalebar(breaks = c(0, 1, 2), text.size = 1, 
               position = c(&quot;left&quot;, &quot;bottom&quot;)) +
    tm_title(&quot;Percent white Sacramento tracts&quot;) +
    tm_layout(scale = 0.6)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-68-1.png" /><!-- --></p>
<p>The argument <code>breaks</code> within <code>tm_scalebar()</code>
tells R the distances to break up and end the bar. Make sure you use
reasonable break points. Sacramento is not, for example, 500 miles wide,
so you should not use <code>c(0,10,500)</code> (try it and see what
happens. You won’t like it). Note that the scale is in miles (were in
America!). The default is in kilometers (the rest of the world!), but
you can specify the units within <code>tm_shape()</code> using the
argument <code>unit</code>. Here, we used <code>unit = "mi"</code>. The
<code>position =</code> argument locates the scale bar on the bottom
left of the map. The argument <code>text.size  =</code> controls the
size of the scale bar.</p>
<p><br></p>
<p>We can also add a north arrow, which we can add using the function
<code>tm_compass()</code>. You can control for the type, size and
location of the arrow within this function. We place a 4-star arrow on
the bottom right of the map.</p>
<pre class="r"><code>tm_shape(saccitytracts, unit = &quot;mi&quot;) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = &quot;reds&quot;),
              fill.legend = tm_legend(title = &quot;Percent white&quot;,
                            position = tm_pos_out(&quot;right&quot;, &quot;center&quot;))) +
    tm_scalebar(breaks = c(0, 1, 2), text.size = 1, 
               position = c(&quot;left&quot;, &quot;bottom&quot;)) +
    tm_title(&quot;Percent white Sacramento tracts&quot;) +
    tm_compass(type = &quot;4star&quot;, 
               position = tm_pos_in(&quot;right&quot;, &quot;bottom&quot;)) +
    tm_layout(scale = 0.6)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-69-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="dot-map" class="section level4">
<h4><strong>Dot map</strong></h4>
<p><br />
</p>
<p>OSU talks about dot maps on pages 66-71. We can create a dot or pin
map using <code>tm_dots()</code>. Let’s do so for EV chargers in
Sacramento. We’ll overlay it on top of Sacramento city tract
borders.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_borders()  +
tm_shape(evcharge) +
  tm_dots(fill = &quot;red&quot;) +
  tm_title(&quot;EV Charge Stations Sacramento&quot;) +
  tm_layout(scale = 0.6)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-70-1.png" /><!-- --></p>
<p>Let’s overlay it on top of polygons shaded by percent white.</p>
<pre class="r"><code>tm_shape(saccitytracts, unit = &quot;mi&quot;) +
  tm_polygons(fill = &quot;pwh&quot;,
              fill.scale = tm_scale(style = &quot;quantile&quot;,
                                    values = &quot;reds&quot;),
              fill.legend = tm_legend(title = &quot;Percent white&quot;,
                            position = tm_pos_out(&quot;right&quot;, &quot;center&quot;))) +
  tm_shape(evcharge) +
  tm_dots(fill = &quot;black&quot;) +
  tm_title(&quot;EV Charge Stations Sacramento&quot;) +
  tm_layout(scale = 0.6) +
  tm_scalebar(breaks = c(0, 1, 2), text.size = 1, 
               position = c(&quot;left&quot;, &quot;bottom&quot;)) +
  tm_compass(type = &quot;4star&quot;, 
               position = tm_pos_in(&quot;right&quot;, &quot;bottom&quot;)) +
  tm_layout(scale = 0.6)</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-71-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="color-patch-map" class="section level4">
<h4><strong>Color patch map</strong></h4>
<p><br />
</p>
<p>OSU page 72 discusses color patch maps, which is a map of polygons
based on a categorical variable. To do this, use
<code>tm_scale_categorical()</code> for the <code>fill.scale =</code>
argument. Let’s map the categorical variable <em>medinc</em>, which has
categories “High”, “Medium” and “Low”.</p>
<pre class="r"><code>tm_shape(saccitytracts) +
  tm_polygons(fill = &quot;medinc&quot;,
              fill.scale = tm_scale_categorical(values=&quot;Paired&quot;),
              fill.legend = tm_legend(position = tm_pos_out(&quot;right&quot;, &quot;center&quot;))) +
  tm_title(&quot;Median Income Sacramento&quot;) </code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-72-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="cartogram" class="section level4">
<h4><strong>Cartogram</strong></h4>
<p><br />
</p>
<p>In R, a useful implementation of different types of cartograms is
included in the package <strong>cartogram</strong>. Specifically, this
supports the area cartograms described in OSU page 78 using
<code>cartogram_cont()</code>. The result of these functions is a simple
features layer, which can then be mapped by means of the usual
<strong>tmap</strong> commands.</p>
<p>For example, we take the <em>pwh</em> variable to construct an area
cartogram. First, we need to add a <a
href="https://pro.arcgis.com/en/pro-app/2.7/help/mapping/properties/coordinate-systems-and-projections.htm">projection</a>
to <em>saccitytracts</em>. We do this by using
<code>st_transform()</code>, and we use the <a
href="https://gisgeography.com/utm-universal-transverse-mercator-projection/">UTM
projection</a>.</p>
<pre class="r"><code>saccitytracts &lt;-st_transform(saccitytracts, 
                              crs = &quot;+proj=utm +zone=10 +datum=NAD83 +ellps=GRS80&quot;) </code></pre>
<p>Next, we pass the layer (<em>saccitytracts</em>) and the variable to
the <code>cartogram_cont</code> function. We check that the result is an
<strong>sf</strong> object.</p>
<pre class="r"><code>carto.cont &lt;- cartogram_cont(saccitytracts,&quot;pwh&quot;)
class(carto.cont)</code></pre>
<p>Which we can map. Is the cartogram a useful visual tool for a
variable like percent white?</p>
<pre class="r"><code>tm_shape(carto.cont, unit = &quot;mi&quot;) +
    tm_polygons(fill = &quot;pwh&quot;,
                fill.scale = tm_scale(style = &quot;quantile&quot;,
                                      values = &quot;reds&quot;),
                fill.legend = tm_legend(title = &quot;Percent white&quot;,
                                        position = tm_pos_out(&quot;right&quot;, &quot;center&quot;)))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-75-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="visualizing-raster-data" class="section level4">
<h4><strong>Visualizing raster data</strong></h4>
<p><br />
</p>
<p>In <strong>tmap</strong>, single-band raster data are symbolized
using <code>tm_raster()</code>. Here, we plot the raster data set
<em>elev</em> we brought earlier, which represents elevation in
Luxembourg.</p>
<pre class="r"><code>tm_shape(elev)+
  tm_raster()</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-76-1.png" /><!-- --></p>
<p>We can use all the same features discussed above for areal data with
raster data. For example, we can adjust the <code>style</code> using
<code>tm_scale_intervals()</code>.</p>
<pre class="r"><code>tm_shape(elev)+
  tm_raster(col.scale = tm_scale_intervals(style = &quot;quantile&quot;))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-77-1.png" /><!-- --></p>
<p>If you do not want to group colors into ranges or bins, you can use
the continuous method where a color ramp is used to display the data
without binning. This is done using
<code>tm_scale_continuous()</code>.</p>
<pre class="r"><code>tm_shape(elev)+
  tm_raster(col.scale = tm_scale_continuous())</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-78-1.png" /><!-- --></p>
<p>We can also adjust the color. Here, we use <code>brewer.pal</code>
within <code>values =</code> to obtain a grey color scheme.</p>
<pre class="r"><code>tm_shape(elev)+
  tm_raster(col.scale = tm_scale_intervals(style = &quot;quantile&quot;,
                                           n=7, values = brewer.pal(&quot;Greys&quot;, n = 7)))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-79-1.png" /><!-- --></p>
<p>We can also visualize categorical raster data. First, lets create a
raster with a categorical variable, in this case regional name.</p>
<pre class="r"><code>region &lt;- rasterize(lux, r, &#39;NAME_2&#39;)</code></pre>
<p>Next, we can map this variable by setting the style argument equal to
<em>cat</em>.</p>
<pre class="r"><code>tm_shape(region)+
  tm_raster(col.scale = tm_scale_categorical(),
            col.legend = tm_legend(title = &quot;Region&quot;))</code></pre>
<p><img
src="introspatial_files/figure-html/unnamed-chunk-81-1.png" /><!-- --></p>
<p>Of course, region is a bit of a trivial example of a raster
categorical variable. Something like <a
href="https://www.usgs.gov/centers/eros/science/national-land-cover-database">land
cover</a> type or a variable that is spatially granular or best
represented as a grid is a better use of a raster categorical
representation.</p>
<p>Note that all the map adjustments and additional features we went
through above for vector data also apply for making maps of raster
objects.</p>
<p><a
href="https://www.youtube.com/watch?v=3GwjfUFyY6M">Congratulations</a>
for getting through the lab guide! Answer the Assignment 5 questions
that are uploaded on Canvas. Submit an R Markdown and its knitted
document on Canvas by the assignment due date.</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
</div>
<div id="old-spatial-packages" class="section level2">
<h2><strong>Old spatial packages</strong></h2>
<p><br />
</p>
<p>If you search online for help and resources on spatial data in R, you
will find information on a number of older packages that users relied on
to process, wrangle and analyze spatial data. Before the
<strong>sf</strong> package was developed, the <strong>sp</strong>
package was used to represent and work with vector spatial data. This
package is still used to some extent, but is getting phased out by
<strong>sf</strong>. Nevertheless, if you are confronted with managing
spatial data in the <strong>sp</strong> world, check out their official
<a href="https://cran.r-project.org/web/packages/sp/index.html">CRAN
page</a>. The <code>st_as_sf()</code> function in <strong>sf</strong>
can be used to transform an <strong>sp</strong> object to an
<strong>sf</strong> object. The package prior to <strong>terra</strong>
that was used for processing raster data was <strong>raster</strong>.
<strong>sp</strong> as well as the <strong>rgdal</strong>,
<strong>rgeos</strong>, <strong>raster</strong> and
<strong>maptools</strong> packages are no longer maintained and will
retire.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="resources" class="section level2">
<h2><strong>Resources</strong></h2>
<p><br />
</p>
<p>This is not a <strong>G</strong>eographic
<strong>I</strong>nformation <strong>S</strong>cience class, so we did
not touch on the many tools that <strong>sf</strong> and
<strong>terra</strong> offer for manipulating and managing your spatial
data. The best references for cleaning, managing and analyzing spatial
data in R are <a
href="https://geocompr.robinlovelace.net/">Geocomputation with R</a>
(GWR) and <a href="https://r-spatial.org/book/">Spatial Data Science</a>
(SDS). Both are freely available through the links provided.</p>
<p>For more on using <code>ggplot()</code> to map, check out <a
href="https://ryanpeek.org/2017-11-05-mapping-with-sf-Part-2/">this</a>
and <a
href="https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html">this</a>.</p>
<hr />
<p><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This
work is licensed under a
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative
Commons Attribution-NonCommercial 4.0 International License</a>.</p>
<p>Website created and maintained by <a
href="https://nbrazil.faculty.ucdavis.edu/">Noli Brazil</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>


</body>
</html>
