<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Kenji Tomari" />


<title>Lab Lecture - Week 2</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 66px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h2 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h3 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h4 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h5 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h6 {
  padding-top: 71px;
  margin-top: -71px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">GEO 200CN: Winter 2020</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
<li>
  <a href="hw_guidelines.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Labs
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="getting_started.html">Getting Started</a>
    </li>
    <li>
      <a href="tidyr.html">Intro to tidyverse</a>
    </li>
    <li>
      <a href="central.html">Sampling, CIs, CLT</a>
    </li>
    <li>
      <a href="hypothesis.html">Hypothesis Testing</a>
    </li>
    <li>
      <a href="spatialsf.html">Mapping in sf</a>
    </li>
    <li>
      <a href="pointpatterns.html">Point Pattern Analysis</a>
    </li>
    <li>
      <a href="spatialautocorrelation.html">Spatial Autocorrelation</a>
    </li>
    <li>
      <a href="linearregression.html">Linear Regression I</a>
    </li>
    <li>
      <a href="linearregression2.html">Linear Regression II</a>
    </li>
    <li>
      <a href="spatialreg.html">Spatial Regression</a>
    </li>
    <li>
      <a href="spatialheterogeneity.html">Spatial Heterogeneity</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Lab Lectures
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lab_Week1.html">Lab Lecture - 1</a>
    </li>
    <li>
      <a href="Lab_Week2.html">Lab Lecture - 2</a>
    </li>
    <li>
      <a href="Lab_Week3.html">Lab Lecture - 3</a>
    </li>
    <li>
      <a href="Lab_Week4.html">Lab Lecture - 4</a>
    </li>
    <li>
      <a href="Lab_Week5.html">Lab Lecture - 5</a>
    </li>
    <li>
      <a href="Lab_Week6.html">Lab Lecture - 6</a>
    </li>
    <li>
      <a href="Lab_Week7.html">Lab Lecture - 7</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a></a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Lab Lecture - Week 2</h1>
<h3 class="subtitle">Spring 2020</h3>
<h4 class="author">Kenji Tomari</h4>

</div>


<div id="reminders" class="section level1">
<h1>Reminders</h1>
<p>Don’t forget about the <a href="https://rstudio.com/resources/cheatsheets/">cheatsheets</a>!</p>
</div>
<div id="functions" class="section level1">
<h1>Functions</h1>
<p>Reading: <a href="https://rspatial.org/intr/8-functions.html">rspatial</a>.</p>
<p><strong>Key Points</strong></p>
<ul>
<li>Functions are like machines, they take in some input (i.e. arguments), they have some settings that change the behavior of the machine (i.e. arguments), and they produce an output (i.e. returns values).</li>
<li>Most functions have “named arguments,” although there are a few unnamed arguments like <code>...</code>.</li>
<li>You can make your own function, using the function: <code>function()</code>.</li>
<li>You can name your function so it can be stored in the environment, or you can just have it run once in your code as you won’t need it later. The latter functions are called “anonymous.”</li>
</ul>
<hr />
<p>We’ve already gone over some existing functions in Week 1, such as <code>mean()</code>, <code>c()</code>, and <code>data.frame()</code>. Remember, these functions come bundled with R, but you can also make your own functions. But first, let’s think about the structure of the function in R.</p>
<p>You can think of functions as machines: they (generally) take in some sort of input (sort of like unprocessed cotton into a cotton gin), the machine has some settings, and then they spit something out (like cotton fibers separated from seeds). Each function also has a unique name.</p>
<p>More formally, functions “take arguments,” this includes the raw material and the settings, and then they “return a value.”</p>
<p>In the below function, we’ll take the mean of <code>some_numbers</code>.</p>
<pre class="r"><code># first, we&#39;ll create a vector that we want to supply to the function
some_numbers &lt;- c(5,NA,3)

# then we run the function
mean(some_numbers)</code></pre>
<pre><code>## [1] NA</code></pre>
<p>You’ll note that it spits out <code>NA</code>. This is because <code>mean()</code> doesn’t know what to do with the 2nd value in <code>some_numbers</code> without some guidance.</p>
<pre class="r"><code>mean(some_numbers, na.rm = T)</code></pre>
<pre><code>## [1] 4</code></pre>
<p>You’ll notice that in the above modified version we have a new “argument,” <code>na.rm = T</code>. The structure of an argument is such: there a name for the argument, the <code>=</code> operator to assign the value, and then the value of the argument, in this case <code>TRUE</code>. Importantly, <code>na.rm</code> is the “name” of the argument. You’ll note, that the first argument, <code>some_numbers</code> is unnamed. We could name it.</p>
<pre class="r"><code>mean(x = some_numbers,
     na.rm = T)</code></pre>
<pre><code>## [1] 4</code></pre>
<p>I didn’t arbitrarily “name” the first argument as <code>x</code>. The name <code>x</code> is the name for the first argument. Read more in the Help tab (type <code>?mean</code>). The reason why earlier we didn’t need to name the argument (i.e. <code>mean(some_numbers, na.rm=T)</code>) is because the ORDER of the arguments matter UNLESS they are named explicitly.</p>
<div id="making-functions" class="section level2">
<h2>Making Functions</h2>
<p>I like naming functions starting with a prefix, <code>fn_</code>, just because I can better keep track of my functions that way. But you can name your functions any way you like.</p>
<p>To create a function, we use the function that creates functions, called—strangely enough—<code>function()</code>.</p>
<pre class="r"><code># fn name            arguments
fn_adder &lt;- function(a, b){
  # return
  sum(a,b)
}

fn_adder(5,3)</code></pre>
<pre><code>## [1] 8</code></pre>
<p>You’ll note I use a function (<code>sum</code>) inside a function. I could also have just done <code>a+b</code>.</p>
<p>Importantly, the “value” that gets “returned” (i.e. the output) typically occurs on the last line of the function. This is not universally true, and I’ll show you what I mean when we get to “decision making” (called branching in rspatial). You can also use the function <code>return()</code> to explicitly tell the function the thing you want as the “output,” but by convention R coders do not use it except when they absolutely must. We will come across an example of this “decision making.”</p>
<p>Here’s another example with text.</p>
<pre class="r"><code>fn_short_madlib &lt;- function(noun1, 
                            verb_present_participle, 
                            noun2){
  print(
    paste0(
      &quot;There is a &quot;, 
      noun1,
      &quot; &quot;,
      verb_present_participle, 
      &quot; Europe.&quot;
    )
  )
}

fn_short_madlib(&quot;dog&quot;, &quot;exploring&quot;)</code></pre>
<pre><code>## [1] &quot;There is a dog exploring Europe.&quot;</code></pre>
<p>One final note, rspatial describes a special argument <code>...</code>, but this is a little advanced. We will not be asking you to create a function with <code>...</code>, but we will ask you to use several functions that use <code>...</code> as an argument. For instance, the function <code>c()</code>’s main input argument is <code>...</code> because it doesn’t matter how many values with which you supply it. CHeck out it’s documentation, <code>?c</code>.</p>
<pre class="r"><code>c(1,2,3,4,5,6,7,8,9,10,11)</code></pre>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10 11</code></pre>
<hr />
<p><em>Supplemental</em></p>
<ul>
<li><a href="https://www.tutorialspoint.com/r/r_functions.htm">Tutorials Point on Functions</a></li>
</ul>
</div>
</div>
<div id="apply-functionals" class="section level1">
<h1>Apply Functionals</h1>
<p><strong>Key Concepts</strong></p>
<ul>
<li>The apply family of functions all do similar things: run a function over a series of values, like a column in a data.frame.</li>
<li>There are many variations of apply functions, usually differentiated by the R object that they work on or they produce, for instance do they work on matrices? Do they spit out vectors?</li>
<li>Many of the complicated capabilities of apply functions can be done more easily and written in code that is easier to read to other programmers using a toolset (i.e. package) called the <code>tidyverse</code>, however it’s still good to learn the basics of the apply family of functions as they are fast and efficient and used in more advanced use cases.</li>
</ul>
<hr />
<p>Apply is a whole family of functions that serve one key purpose, doing something iteratively over a series of values. Apply functions actually belongs to a special group of functions, called “functionals.” (Read the word “functional” as a noun, not an adjective.) Functionals are functions that take another function as an input OR returns a function. Don’t worry about getting your head wrapped around that last sentence, just understand that the family of functions we like to call the “apply functionals” are a little more advanced than other functions.</p>
<div id="apply" class="section level2">
<h2><code>apply</code></h2>
<p>There are several functions that belong to the apply family, including <code>apply</code>, <code>tapply</code>, <code>lapply</code>, <code>sapply</code>, and <code>vapply</code>. We’ll start with the most basic one, <code>apply</code>.</p>
<p>Let’s take a look at an example.</p>
<pre class="r"><code># first create a matrix upon which to use apply over.
my_matrix &lt;- matrix(
  # values 3 through 12 as a vector
  data = 3:12, 
  # an argument that specifies # of columns
  ncol = 2, 
  # fill the values of this 2 col matrix by row
  byrow = T
)    

my_matrix</code></pre>
<pre><code>##      [,1] [,2]
## [1,]    3    4
## [2,]    5    6
## [3,]    7    8
## [4,]    9   10
## [5,]   11   12</code></pre>
<p>The purpose of <code>apply</code> is to do something over a matrix. The thing you “do” is a function, and you get to choose if you want to run the function across a row or column. A simple example might be to take the average of each column.</p>
<pre class="r"><code>apply(
  # the matrix object that composes the input values
  X = my_matrix,
  # over the row or column? 1 for row, 2 for column
  MARGIN = 2,
  # what function should we use?
  FUN = mean      
)</code></pre>
<pre><code>## [1] 7 8</code></pre>
<p>You’ll see it spits out two values, one for each column. This is just like if you ran the function <code>mean()</code> over two different vectors, and then combined the answers. Like so:</p>
<pre class="r"><code>c(
  mean(c(3, 5, 7, 9, 11)),
  mean(c(4, 6, 8, 10, 12))
)</code></pre>
<pre><code>## [1] 7 8</code></pre>
<p>So, just to reiterate: apply functions take both an object (i.e. values) and a function which to use over this object. The fact that it takes in functions as an argument is why this is a “functional”.</p>
<p>Note, when you supply a function to <code>apply</code> for the named argument <code>FUN</code>, you can either type <code>mean</code> without any parenthesis or <code>&quot;mean&quot;</code> with quotation marks.</p>
</div>
<div id="apply-your-own-functions" class="section level2">
<h2>Apply your own functions</h2>
<p>You need not be constrained to functions provided to you by others. Use your own functions. There are two ways to do this. You can either create a function much as you have before, or use an “anonymous” function that has no name. Anonymous functions disappear after they get used. If you check the Environment tab, you’ll note that named functions stick around in the Environment, but “anonymous” functions do not.</p>
<p>Here we see examples for each below. In this example, I am just adding numbers to each cell in the matrix (whereas before we were doing something to all of the values in a column or row together, like adding them all up or taking the average of all the values).</p>
<pre class="r"><code># Your own function - Example 1.
# named function
fn_add_three &lt;- function(input_value){
  input_value + 3
}

# apply the fn_add_two function over my_matrix by column
apply(
  my_matrix,
  2,
  fn_add_three
)</code></pre>
<pre><code>##      [,1] [,2]
## [1,]    6    7
## [2,]    8    9
## [3,]   10   11
## [4,]   12   13
## [5,]   14   15</code></pre>
<p>Note, if you changed the value of <code>MARGIN</code> from <code>2</code> to <code>1</code> it converts each column into a row. Since we want to keep it in the same form, I used <code>2</code>.</p>
<pre class="r"><code># Your own function - Example 2.
# anonymous functions
apply(
  X = my_matrix,
  MARGIN = 2,
  FUN = function(input_value) {
    input_value + 3
  }
)</code></pre>
<pre><code>##      [,1] [,2]
## [1,]    6    7
## [2,]    8    9
## [3,]   10   11
## [4,]   12   13
## [5,]   14   15</code></pre>
<p>Please note that the “value” being passed to the function when you use <code>apply</code> is the whole row or vector. In the example above where 3 is added to each cell in the matrix, it may seem like the calcuation is happening to one cell at a time, but what is actually happening (for the first column) is <code>c(3,5,7,9,11) + 3</code>. As a proof of concept, we use the <code>length</code> function to find out exactly how many values are in <code>x</code>:</p>
<pre class="r"><code>apply(
  X = my_matrix,
  MARGIN = 2,
  FUN = function(x){
    length(x)
  })</code></pre>
<pre><code>## [1] 5 5</code></pre>
<p>This is why when we use <code>mean</code> it gives us the mean of the whole column (or row) and not the mean of each cell (which would be itself, and thus useless).</p>
</div>
<div id="tapply" class="section level2">
<h2><code>tapply</code></h2>
<p>What if we have a data.frame like <code>iris</code> and we want to summarise some information by category? In the <code>iris</code> dataset, we have 3 species with 50 observations of various anatomical parts, like the length of a petal.</p>
<pre class="r"><code># load iris dataset
data(iris)
# first six values
head(iris)</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<p>Let’s say we want the average <code>Petal.Length</code> for each species. How do we get this?</p>
<pre class="r"><code>tapply(
  X = iris$Petal.Length,
  INDEX = iris$Species,
  FUN = mean
)</code></pre>
<pre><code>##     setosa versicolor  virginica 
##      1.462      4.260      5.552</code></pre>
</div>
<div id="aggregate" class="section level2">
<h2><code>aggregate</code></h2>
<p>Much like <code>tapply</code>, <code>aggregate</code> summarizes variables by category. It has the added bonus of being able to handle multiple columns at a time. This function also contains a lot of options. However, it isn’t exactly user-friendly. We’ll learn other ways of doing what <code>aggregate</code> does later when we learn <code>{tidyverse}</code></p>
<pre class="r"><code>aggregate(
  # object to apply some function over
  # here I subset the iris dataset
  x = iris[
    c(
      &quot;Sepal.Length&quot;,
      &quot;Sepal.Width&quot;,
      &quot;Petal.Length&quot;, 
      &quot;Petal.Width&quot; 
    )
  ],
  # column with grouping variable.
  # note, `by` accepts `lists`
  by = list(
    iris$Species  # the $ makes this a vector
  ),
  # function to apply over columns
  FUN = mean,
  # should each summarized subset be simplified?
  simplify = T,
  # remove any NA values
  na.rm = T
)</code></pre>
<pre><code>##      Group.1 Sepal.Length Sepal.Width Petal.Length Petal.Width
## 1     setosa        5.006       3.428        1.462       0.246
## 2 versicolor        5.936       2.770        4.260       1.326
## 3  virginica        6.588       2.974        5.552       2.026</code></pre>
</div>
<div id="lapply" class="section level2">
<h2><code>lapply</code></h2>
<p><em>advanced</em></p>
<p>While there are still other functions like <code>apply</code>, I’ll just go over one more that I use quite often. The function <code>lapply</code> applies a function over a list or vector, and returns a <code>list</code> object as a result.</p>
<p>Let’s take an example using <code>iris</code> again. Here I’ll split <code>iris</code> up into three separate <code>data.frames</code> and store them in a <code>list</code> for demonstration purposes.</p>
<pre class="r"><code># Here I split up the data.frame called iris into three list elements.
my_list &lt;- list(
  # sp. setosa
  iris_setosa = iris[iris$Species == &quot;setosa&quot;,],
  # sp. versicolor
  iris_versicolor = iris[iris$Species == &quot;versicolor&quot;,],
  # sp. virginica
  iris_virginica = iris[iris$Species == &quot;virginica&quot;,]
)</code></pre>
<p>Let’s say I had this <code>list</code>, but didn’t know what it contained. I could use <code>lapply</code> to find out what type of R object each element is. The function I’ll apply is <code>class</code> which tells me the Atomic type if the input is a vector, or the type of structured data the input is if it is not a vector (e.g. <code>list</code>, <code>data.frame</code>, <code>matrix</code>).</p>
<pre class="r"><code>lapply(
  X = my_list,
  FUN = class
)</code></pre>
<pre><code>## $iris_setosa
## [1] &quot;data.frame&quot;
## 
## $iris_versicolor
## [1] &quot;data.frame&quot;
## 
## $iris_virginica
## [1] &quot;data.frame&quot;</code></pre>
<p>Oh look! They’re all data.frames. Now I would like to see the first row of each of these data.frames:</p>
<pre class="r"><code>print(
  lapply(
    X = my_list,
    FUN = function(x) {
      x[1,]
    }
  )
)</code></pre>
<pre><code>## $iris_setosa
##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 
## $iris_versicolor
##    Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
## 51            7         3.2          4.7         1.4 versicolor
## 
## $iris_virginica
##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 101          6.3         3.3            6         2.5 virginica</code></pre>
<p>In the above code, I took <code>my_list</code> then applied a function that created a subset from each of the three elements. The subset was just the first row. Then, I used <code>print</code> to display them on the screen.</p>
<p>Admittedly, <code>lapply</code> is more for advanced users, but I like it because sometimes I need to split my data up and do weird things to it. Or sometimes I get a bunch of data already split up. In which case, I use <code>read.csv</code> to load each csv file into a <code>list</code> element, just like the three above. Then I’ll do whatever I need to do to each <code>list</code> element and bring it all back together.</p>
<p>For example, if I wanted to first take the average of <code>Petal.Length</code> for each species, and then make a single <code>data.frame</code> I could do this.</p>
<pre class="r"><code># First we create a list of three data.frames
my_list &lt;- lapply(
  X = my_list,
  FUN = function(x) {
    # create a data.frame to return.
    data.frame(
      # Species Column
      Species = x$Species[1],
      # Mean Petal Length column
      Mean.Petal.Length = mean(x$Petal.Length)
    )  # end of data.frame()
  }  # end of anonymous function
)  # end of lapply()

print(my_list)</code></pre>
<pre><code>## $iris_setosa
##   Species Mean.Petal.Length
## 1  setosa             1.462
## 
## $iris_versicolor
##      Species Mean.Petal.Length
## 1 versicolor              4.26
## 
## $iris_virginica
##     Species Mean.Petal.Length
## 1 virginica             5.552</code></pre>
<pre class="r"><code># Second we use a special function to combine all the
# list elements.
do.call(rbind, my_list)</code></pre>
<pre><code>##                    Species Mean.Petal.Length
## iris_setosa         setosa             1.462
## iris_versicolor versicolor             4.260
## iris_virginica   virginica             5.552</code></pre>
<p>You’ll note we could have done the above in <code>tapply</code> or <code>aggregate</code>. My point was not that this is the easiest way to get a summary statistic for each species, just that this is another way to do so.</p>
<p><em>Supplemental</em></p>
<ul>
<li><a href="http://adv-r.had.co.nz/Functionals.html">Advanced R - Functionals</a></li>
<li><a href="https://purrr.tidyverse.org/">purrr</a> - The “tidy” way to iteratively apply a function over a series of values.</li>
</ul>
</div>
</div>
<div id="flow-control" class="section level1">
<h1>Flow Control</h1>
<p>Much like the apply family of functions, loops serve to do something iteratively. They’re more flexible, though they tend to be a little slower depending on the task at hand. Historically, loops were the main way you did repetitive tasks, and they remain a cornerstone of programming more generally. A good rule of thumb is, if you can do something without too much effort using an apply function (beyond the initially steep learning curve), use an apply function. For other cases, use a loop.</p>
<div id="for-loops" class="section level2">
<h2>For Loops</h2>
<p>The basic structure of a <code>for</code> loop is fairly straight forward. You begin by calling the function <code>for()</code>, which takes an “expression” as an argument in the following form: a variable for each element in a series of values. <code>for</code> loops always execute sequentially.</p>
<p>Here are some simple examples of <code>for</code> loops.</p>
<pre class="r"><code>for(i in 1:10) {
  print(i)
}</code></pre>
<pre><code>## [1] 1
## [1] 2
## [1] 3
## [1] 4
## [1] 5
## [1] 6
## [1] 7
## [1] 8
## [1] 9
## [1] 10</code></pre>
<p>In the above, the variable <code>i</code> takes on the first value in the sequence <code>1:10</code> (i.e. <code>1</code>), then repeats the instruction in the curly braces, all the way through <code>10</code>.</p>
<p>In case you want to see this in action, you can slow things down by pausing after printing the value of <code>i</code>.</p>
<pre class="r"><code>for(i in 1:10){
  print(i)
  Sys.sleep(1)  # pauses for 1 second.
}</code></pre>
<p>You might notice that:</p>
<pre class="r"><code>i == 10</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>The variable <code>i</code> persists beyond the <code>for</code> loop.</p>
<p><code>for</code> loops don’t need just go through a series of numbers.</p>
<pre class="r"><code># a character vector
values &lt;- c(&quot;Rosa&quot;, &quot;Karl&quot;, &quot;Sylvia&quot;)

# a for loop
for(x in values){
  print(paste0(
    &quot;Hello &quot;,
    x,
    &quot;!&quot;
  ))
}</code></pre>
<pre><code>## [1] &quot;Hello Rosa!&quot;
## [1] &quot;Hello Karl!&quot;
## [1] &quot;Hello Sylvia!&quot;</code></pre>
<p>(The <code>paste0</code> function just takes a bunch of different pieces of text and smashes it together without spaces. If you wanted spaces in between the text, use <code>paste</code>.)</p>
<p>Tangent: By convention when you iterate through a sequence of numbers, we use the variable names <code>i</code>, <code>j</code>, or <code>k</code>; when we iterate through a series of values that are not in a sequence, like a list of people’s names, we use <code>x</code>, <code>y</code>, or <code>z</code>. Of course this convention makes no difference to R.</p>
<p>If you want to clean up your environment after a <code>for</code> loop, consider adding this line below the end of the loop:</p>
<pre class="r"><code>rm(i)</code></pre>
</div>
<div id="while-loops" class="section level2">
<h2>While Loops</h2>
<p>While loops are functioning the same, they just operate in a slightly different way. They continue repeating until the expression in the parentheses of <code>while()</code> becomes untrue, or you tell it to quit it.</p>
<pre class="r"><code># a variable that I use to keep track of iterations.
counter &lt;- 5
# while loop
while(counter != 0){
  print(counter)
  # decrease the value of counter by one
  counter &lt;- counter - 1
}</code></pre>
<pre><code>## [1] 5
## [1] 4
## [1] 3
## [1] 2
## [1] 1</code></pre>
<p>You can also do things like skip around or end a loop early. This is true for <code>for</code> loops as well. In the example below I use “decision making” or “branching,” which I’ll explain in more detail in the next section. In short, it allows me to make a choice.</p>
<p>In order to skip to the next iteration, use <code>next</code> and in order to terminate the loop altogether, use <code>break</code>.</p>
<pre class="r"><code>counter &lt;- 0

while(counter &lt;= 10){
  
  # add one to counter
  counter &lt;- counter + 1
  
  # skip if counter == 5
  if(counter == 5){
    # the skip to next iteration function
    next()
  }
  
  # end loop early if counter == 7
  if(counter == 7){
    break()
  }
  
  print(counter)
}</code></pre>
<pre><code>## [1] 1
## [1] 2
## [1] 3
## [1] 4
## [1] 6</code></pre>
<p>You’ll note, it does indeed skip 5 and ends before 7 is printed.</p>
<p>Finally, loops can go on forever if you like. Just make sure the expression in <code>while()</code> is equal to true. You could use <code>while(1==1)</code>, i.e. while one is equal to 1; or you could create a <code>counter</code> variable equal to 1, and have the expression read <code>while(counter == 1)</code> and then refuse to adjust the value of <code>counter</code>; or just do:</p>
<pre class="r"><code># don&#39;t execute this code without reading below...
while(TRUE){
  print(&quot;Infinite Loop!&quot;)
  Sys.sleep(3)
}</code></pre>
<p>If you ever need stop code from continuing to execute, just hit the CTRL + C keys or the ESC key. Here’s a more useful example of an infinite loop. We’ll describe some of its components in more detail in the next section.</p>
<pre class="r"><code>random_value &lt;- sample(5:10, 1)
print(random_value)</code></pre>
<pre><code>## [1] 10</code></pre>
<pre class="r"><code>while(TRUE){
  # decrease value
  random_value &lt;- random_value - 1
  
  # break.
  if(random_value == 0){
    print(&quot;Oh look, we&#39;re all done.&quot;)
    break()
  }
  
  print(&quot;I&#39;ll keep going for now.&quot;)
}</code></pre>
<pre><code>## [1] &quot;I&#39;ll keep going for now.&quot;
## [1] &quot;I&#39;ll keep going for now.&quot;
## [1] &quot;I&#39;ll keep going for now.&quot;
## [1] &quot;I&#39;ll keep going for now.&quot;
## [1] &quot;I&#39;ll keep going for now.&quot;
## [1] &quot;I&#39;ll keep going for now.&quot;
## [1] &quot;I&#39;ll keep going for now.&quot;
## [1] &quot;I&#39;ll keep going for now.&quot;
## [1] &quot;I&#39;ll keep going for now.&quot;
## [1] &quot;Oh look, we&#39;re all done.&quot;</code></pre>
</div>
<div id="decision-making-branching" class="section level2">
<h2>Decision Making (Branching)</h2>
<p>We’ve already demonstrated some decision making, but here I’ll go into it in more depth.</p>
<p>Decisions are made with the functions <code>if</code>, <code>else if</code>, and <code>else</code>. (There is a function called <code>elseif</code> that can also be used, but this is discouraged. <em>Advanced:</em> in the <code>tidyverse</code>, you can use the function <code>case_when</code> as well.)</p>
<p>For code to execute, the expression in the <code>if</code> statement must be evaluate to <code>TRUE</code>.</p>
<pre class="r"><code>if(TRUE) {
  print(&quot;It&#39;s true!&quot;)
}</code></pre>
<pre><code>## [1] &quot;It&#39;s true!&quot;</code></pre>
<pre class="r"><code>if(FALSE) {
  print(&quot;This will never print.&quot;)
}</code></pre>
<pre class="r"><code>if(1+2 == 3){
  print(&quot;Yup. The expression `1 + 2 == 3` evaluates to TRUE&quot;)
}</code></pre>
<pre><code>## [1] &quot;Yup. The expression `1 + 2 == 3` evaluates to TRUE&quot;</code></pre>
<p>You can make a decision between two things like so:</p>
<pre class="r"><code>some_value &lt;- 5

if (some_value &gt; 10) {
  print(&quot;This value is larger than 10&quot;)
} else {
  print(&quot;This value is 10 or less.&quot;)
}</code></pre>
<pre><code>## [1] &quot;This value is 10 or less.&quot;</code></pre>
<p>Decide between two or more things with:</p>
<pre class="r"><code>if(some_value &gt; 10) {
  print(&quot;This value is larger than 10&quot;)
  
} else if (some_value == 3.141592654){
  print(&quot;This value is approx. equal to pi.&quot;)
  
} else if (some_value == 5) {
  print(&quot;It&#39;s equal to 5&quot;)
  
} else {
  print(&quot;Wow, its none of the above? How strange.&quot;)
}</code></pre>
<pre><code>## [1] &quot;It&#39;s equal to 5&quot;</code></pre>
<p>You’ll note that <code>else</code> operates like a catchall. You can have code that executes without an <code>else</code> as we saw earlier in the <code>while</code> loop (reproduced below).</p>
<pre class="r"><code>while(TRUE){
  # decrease value
  random_value &lt;- random_value - 1
  
  # break.
  if(random_value == 0){
    print(&quot;Oh look, we&#39;re all done.&quot;)
    break()
  }
  
  print(&quot;I&#39;ll keep going for now.&quot;)
}</code></pre>
<p>In this example we used <code>break</code> to escape an infinite loop, but there are conceivable situations where you need to stop a loop before its conclusion even if it had a definite end iteration on its horizon.</p>
</div>
<div id="decisions-in-functions" class="section level2">
<h2>Decisions in Functions</h2>
<p>Just like in the example above where you <code>break</code> before the conclusion of the loop, functions also sometimes need to return a value before its conclusion. In the example below, we design a function to exit early if either arguments are <code>NA</code>. In order to exit early, we use the function <code>return</code> with the R object we wish the function to produce as output.</p>
<pre class="r"><code>fn_adder &lt;- function(x, y){
  if(is.na(x) | is.na(y)){
    return(NA)
  }
  
  x + y
}

fn_adder(NA, 5)</code></pre>
<pre><code>## [1] NA</code></pre>
<p>The object that is returned could pretty much be anything.</p>
<pre class="r"><code>fn_adder &lt;- function(x,y){
  if(is.na(x) | is.na(y)){
    sentence &lt;- &quot;One or more values are NA.&quot;
    return(sentence)
  }
  
  x + y
}

fn_adder(NA, 5)</code></pre>
<pre><code>## [1] &quot;One or more values are NA.&quot;</code></pre>
</div>
<div id="practical-example" class="section level2">
<h2>Practical Example</h2>
<p>Let’s say we wanted to take the Loblolly dataset and reclassify the age of the trees in the dataset by age groups: 0-4, 5-9, and so on.</p>
<pre class="r"><code>data(&quot;Loblolly&quot;)
head(Loblolly)</code></pre>
<pre><code>## Grouped Data: height ~ age | Seed
##    height age Seed
## 1    4.51   3  301
## 15  10.89   5  301
## 29  28.72  10  301
## 43  41.74  15  301
## 57  52.70  20  301
## 71  60.92  25  301</code></pre>
<pre class="r"><code># For loop
for(i in 1:nrow(Loblolly)){
  
  # get the age for the current iteration
  iteration_age &lt;- as.numeric(Loblolly[i, &quot;age&quot;])
  
  # Decision Making
  if(iteration_age &lt;= 4){
    Loblolly[i, &quot;age&quot;] &lt;- &quot;0-4&quot;
    
  } else if (iteration_age &lt;= 9){
    Loblolly[i, &quot;age&quot;] &lt;- &quot;5-9&quot;
    
  } else if (iteration_age &lt;= 14){
    Loblolly[i, &quot;age&quot;] &lt;- &quot;10-14&quot;
    
  } else if (iteration_age &lt;= 19){
    Loblolly[i, &quot;age&quot;] &lt;- &quot;15-19&quot;
    
  } else if (iteration_age &lt;= 24){
    Loblolly[i, &quot;age&quot;] &lt;- &quot;20-24&quot;
    
  } else if (iteration_age &lt;= 29){
    Loblolly[i, &quot;age&quot;] &lt;- &quot;25-29&quot;
    
  } else {
    Loblolly[i, &quot;age&quot;] &lt;- &quot;Hella Old&quot;
  }
}

head(Loblolly)</code></pre>
<pre><code>## Grouped Data: height ~ age | Seed
##    height   age Seed
## 1    4.51   0-4  301
## 15  10.89   5-9  301
## 29  28.72 10-14  301
## 43  41.74 15-19  301
## 57  52.70 20-24  301
## 71  60.92 25-29  301</code></pre>
<p>Please note, you could have accomplished this with an apply function as well! I’ve used two different apply functions below to demonstrate how this works:</p>
<pre class="r"><code># Simple Version
data(&quot;Loblolly&quot;)

# Here I use sapply, which will always reduce the output
# to the most simple data structure possible.
# For instance, given the choice, sapply will return
# a vector rather than a data.frame.
Loblolly$age &lt;- sapply(
  # input
  X = Loblolly$age,
  # anonymous function
  FUN = function(x){
    # Decision Making
    if(x &lt;= 4){
      &quot;0-4&quot;
      
    } else if (x &lt;= 9){
      &quot;5-9&quot;
      
    } else if (x &lt;= 14){
      &quot;10-14&quot;
      
    } else if (x &lt;= 19){
      &quot;15-19&quot;
      
    } else if (x &lt;= 24){
      &quot;20-24&quot;
      
    } else if (x &lt;= 29){
      &quot;25-29&quot;
      
    } else {
      &quot;Hella Old&quot;
    }
  },  # end of anonymous function
  # Vector elements can actually have &quot;names.&quot;
  # This turns that off.
  USE.NAMES = F
)</code></pre>
<pre class="r"><code># Advanced Version
data(&quot;Loblolly&quot;)

# Here I&#39;m using a vapply, 
# because I expect the output of the apply fn to be a vector.
Loblolly$age &lt;- vapply(
  # the column I want to iterate over
  # Note I use the $ to turn the age column in Loblolly into
  # a vector.
  X = Loblolly$age, 
  # my anonymous function
  FUN = function(x){
    # Decision Making
    if(x &lt;= 4){
      &quot;0-4&quot;
      
    } else if (x &lt;= 9){
      &quot;5-9&quot;
      
    } else if (x &lt;= 14){
      &quot;10-14&quot;
      
    } else if (x &lt;= 19){
      &quot;15-19&quot;
      
    } else if (x &lt;= 24){
      &quot;20-24&quot;
      
    } else if (x &lt;= 29){
      &quot;25-29&quot;
      
    } else {
      &quot;Hella Old&quot;
    }
  },  # end of anonymous function
  # This argument tells vapply what the output
  # of EACH iteration will be, in this case,
  # a character vector of length 1
  FUN.VALUE = character(1),
  # Vector elements can actually have &quot;names.&quot;
  # This turns that off.
  USE.NAMES = F
)</code></pre>
</div>
</div>
<div id="data-prep" class="section level1">
<h1>Data Prep</h1>
<p><strong>Key Concepts</strong></p>
<ul>
<li>Use <code>reshape</code> to restructure data that is NOT yet in a format that we can use. In other words, to create “tidy” data.</li>
<li>Use <code>merge</code> to bring two datasets, with the same individuals under observation, together.</li>
<li>User <code>sort</code> and <code>order</code> to help you sort and rearrange data.</li>
</ul>
<hr />
<div id="reshape" class="section level2">
<h2><code>reshape</code></h2>
<p>Sometimes data doesn’t come in a format that’s readily usable. In other words, it doesn’t follow the “tidy data” convention: “rows as observations” and “columns as variables.” To clarify, the information is all there, but its arranged in a confusing manner. Therefore, we use <code>reshape</code> (or later we use functions from <code>tidyr</code>) to fix this.</p>
<div id="long-to-wide" class="section level3">
<h3>Long to wide</h3>
<p>Imagine we have a dataset like this:</p>
<pre class="r"><code>head(untidy_iris)</code></pre>
<pre><code>##   ID Species  Petal Value
## 1  1  setosa Length   1.4
## 2  1  setosa  Width   0.2
## 3  2  setosa Length   1.4
## 4  2  setosa  Width   0.2
## 5  3  setosa Length   1.3
## 6  3  setosa  Width   0.2</code></pre>
<p>Each observation received an <code>ID</code> number, but they’re split up on two lines! Notice how the <code>Value</code> column is meaningless without the <code>Petal</code> column to indicate what each value is a recorded measurement of. We describe this as “long” data; it is long because the table has more rows than necessary. Compare the <code>nrow</code> of the original iris dataset, 150, versus that of this dataset, 300.</p>
<p>With <code>reshape</code> (and later with functions from <code>tidyr</code>) we can fix this!</p>
<pre class="r"><code>tidied_iris &lt;- reshape(
  # our untidy data
  data = untidy_iris,
  # the &quot;key&quot; variable(s)
  idvar = c(&quot;ID&quot;, &quot;Species&quot;),
  # the column that needs to change.
  timevar = &quot;Petal&quot;,
  # are we adding width to table?
  # or are we adding rows to the table?
  direction = &quot;wide&quot;
)

# now just fix the names
names(tidied_iris)[3:4] &lt;- c(&quot;Petal.Length&quot;, &quot;Petal.Width&quot;)

head(tidied_iris)</code></pre>
<pre><code>##    ID Species Petal.Length Petal.Width
## 1   1  setosa          1.4         0.2
## 3   2  setosa          1.4         0.2
## 5   3  setosa          1.3         0.2
## 7   4  setosa          1.5         0.2
## 9   5  setosa          1.4         0.2
## 11  6  setosa          1.7         0.4</code></pre>
</div>
<div id="wide-to-long" class="section level3">
<h3>Wide to long</h3>
<p>Imagine if you were given the Loblolly dataset, which tracks the height of each tree in a given experimental site as each tree ages. There are a total of 14 different Loblolly Pine trees being measured, over a period of 25 years.</p>
<pre class="r"><code># For demonstration purposes, 
# this just shows the first 4 trees
lob[1:5]</code></pre>
<pre><code>##   age   301   303   305   307
## 1   3  4.51  4.55  4.79  3.91
## 2   5 10.89 10.92 11.37  9.48
## 3  10 28.72 29.07 30.21 25.66
## 4  15 41.74 42.83 44.40 39.07
## 5  20 52.70 53.88 55.82 50.78
## 6  25 60.92 63.39 64.10 59.07</code></pre>
<p>In some ways, this format of data is more pleasing, particularly as it is easy to compare, say, tree 301 to tree 303. However, you’ll notice we no longer follow the “rows as observations” and “columns as variables” structure. If you recall the original <code>Loblolly</code> dataset, there were three columns: <code>height</code>, <code>age</code>, and <code>Seed</code>. Now each <code>Seed</code> has its own column, and so now our table “wide.” We can fix this with <code>reshape</code> as well.</p>
<pre class="r"><code>lob2 &lt;- reshape(
  # Wide data
  data = lob,
  # All the columns that need to be dissolved
  varying = names(lob)[2:15],
  # Name of new column with the groupings in `times`
  timevar = &quot;Seed&quot;,
  # The groupings of Seed
  times = names(lob)[2:15],
  # the name of the new column for the values
  # that previously had no descriptor (just 301, etc)
  v.names = &quot;height&quot;,
  # From wide to long.
  direction = &quot;long&quot;
)

# remove id column &amp; reorder like original Loblolly
lob2 &lt;- lob2[c(3,1,2)]

# remove rownames
rownames(lob2) &lt;- NULL

head(lob2)</code></pre>
<pre><code>##   height age Seed
## 1   4.51   3  301
## 2  10.89   5  301
## 3  28.72  10  301
## 4  41.74  15  301
## 5  52.70  20  301
## 6  60.92  25  301</code></pre>
<p>But wait, wouldn’t each tree be the “observation?” Like one row for each <code>Seed</code>, with 14 rows and 7 columns, include one each for height at some age? We could do this as well, but in the case of the original Loblolly dataset, an observation is identified both by the unique <code>Seed</code> ID number and the <code>age</code>.</p>
<p><em>Supplemental</em></p>
<p><a href="https://r4ds.had.co.nz/tidy-data.html" class="uri">https://r4ds.had.co.nz/tidy-data.html</a></p>
</div>
</div>
<div id="merge" class="section level2">
<h2><code>merge</code></h2>
<p>Sometimes your data is split up into two or more datasets, but contain the same individuals under investigation. For instance, a lot of data from government entities like the US Census data are separated by topic to make accessing those datasets less unwieldy. You might have demographic data based on ethnicity for a US Census tract that you want to combine with economic data you have for that same tract. In which case, you want to join the two datasets together using <code>merge</code> (or, again, functions from the <code>tidyverse</code>).</p>
<p>Imagine that you and your lab partner are measuring a bunch of Iris plants. For each plant you’re in charge of measuring the Iris’ sepals (a anatomical part of the flower), and your partner is measuring the petals. You write this down on a separate piece of paper and enter the data on a separate spreadsheet. Your partner didn’t finish either, they only did 148 Irises. To top it off, you worked in a different order, so while you both each measured the same Irises, your data doesn’t match up when placed side by side.</p>
<p>Here’s what you got:</p>
<pre class="r"><code>head(iris_petals)</code></pre>
<pre><code>##    ID    Species Petal.Length Petal.Width
## 1 609 versicolor          4.5         1.3
## 2 754     setosa          1.7         0.3
## 3 571     setosa          1.6         0.6
## 4 707     setosa          1.4         0.2
## 5 722     setosa          1.4         0.2
## 6 156  virginica          4.5         1.7</code></pre>
<pre class="r"><code>head(iris_sepals)</code></pre>
<pre><code>##    ID   Species Sepal.Length Sepal.Width
## 1 481 virginica          6.1         2.6
## 2 119    setosa          5.1         3.5
## 3 605 virginica          6.2         2.8
## 4 800 virginica          7.2         3.2
## 5 281 virginica          6.3         3.4
## 6 754    setosa          5.7         3.8</code></pre>
<p>R makes resolving this a trivial issue. Here you can use <code>merge</code>.</p>
<pre class="r"><code>all_irises &lt;- merge(
  # first data.frame
  x = iris_sepals,
  # second data.frame
  y = iris_petals,
  # what are the &quot;keys?&quot;
  # i.e. what do they have in common.
  by = c(&quot;ID&quot;, &quot;Species&quot;),
  # This determines which data.frame is
  # considered the primary dataset.
  # When all = T, both are equally important.
  all = T
)

head(all_irises)</code></pre>
<pre><code>##    ID    Species Sepal.Length Sepal.Width Petal.Length Petal.Width
## 1 102  virginica          6.7         3.0          5.2         2.3
## 2 107  virginica          6.3         2.7          4.9         1.8
## 3 109     setosa          5.0         3.4          1.6         0.4
## 4 116     setosa          5.4         3.9          1.7         0.4
## 5 119     setosa          5.1         3.5          1.4         0.2
## 6 122 versicolor          5.6         2.5          3.9         1.1</code></pre>
<p>You’ll note that because your partner only did 148 irises that there are two rows missing petals.</p>
<pre class="r"><code>all_irises[is.na(all_irises$Petal.Length), 
           c(1,2,5,6)]</code></pre>
<pre><code>##     ID   Species Petal.Length Petal.Width
## 17 191 virginica           NA          NA
## 44 367 virginica           NA          NA</code></pre>
<p>What if you wanted only complete rows, and you didn’t need these two individuals with missing Petal data? This where we specify that one of the data.frames is the primary data.frame. In this case, the complete 150 sepals data you collected has superfluous data that can be cast aside.</p>
<pre class="r"><code>partial_irises &lt;- merge(
  # first data.frame
  x = iris_sepals,
  # second data.frame
  y = iris_petals,
  # what are the &quot;keys?&quot;
  # i.e. what do they have in common.
  by = c(&quot;ID&quot;, &quot;Species&quot;),
  # This determines which data.frame is
  # considered the primary dataset.
  # When all = T, both are equally important.
  all.y = T
)</code></pre>
<p>Note, now there are only 148 rows in the merged data.frame. You’ve dropped the 2 rows that are missing in the petals dataset.</p>
<p><em>Supplemental</em></p>
<p><a href="https://r4ds.had.co.nz/relational-data.html" class="uri">https://r4ds.had.co.nz/relational-data.html</a></p>
</div>
<div id="sort-order" class="section level2">
<h2><code>sort</code> &amp; <code>order</code></h2>
<p>Your data may have a certain order to it, but comes to you out of order. Take, by example, the letters of my name. They come out of order. To set them in alphabetical order, we use <code>sort</code></p>
<pre class="r"><code>my_name &lt;- c(&quot;k&quot;, &quot;e&quot;, &quot;n&quot;)
sort(my_name)</code></pre>
<pre><code>## [1] &quot;e&quot; &quot;k&quot; &quot;n&quot;</code></pre>
<p>But, lets say we didn’t want to change the order of my name, we just wanted to know what order it comes in, compared to alphabetical order. In this case, we could use <code>order</code>.</p>
<pre class="r"><code>order(my_name)</code></pre>
<pre><code>## [1] 2 1 3</code></pre>
<p>Here, <code>order</code> has identified that the letter e should come first. That’s why the first value is 2, because it appears as the second letter in <code>c(&quot;k&quot;, &quot;e&quot;, &quot;n&quot;)</code>.</p>
<p>You can re-use the <code>order</code> function in a different (more useful) situation, rearranging your data.frames.</p>
<p>Let’s take the <code>iris</code> dataset and order it by <code>Sepal.Length</code>. In this example, I’ll just show the first 10 values in “Before and After” chunks:</p>
<pre class="r"><code># Before
head(iris)</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<pre class="r"><code># After
head(iris[order(iris$Sepal.Length),])</code></pre>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 14          4.3         3.0          1.1         0.1  setosa
## 9           4.4         2.9          1.4         0.2  setosa
## 39          4.4         3.0          1.3         0.2  setosa
## 43          4.4         3.2          1.3         0.2  setosa
## 42          4.5         2.3          1.3         0.3  setosa
## 4           4.6         3.1          1.5         0.2  setosa</code></pre>
<p>(You may have noticed the unnamed column on the left, the row number, shows you where it used to be.)</p>
</div>
<div id="questions" class="section level2">
<h2>Questions</h2>
<p>What would I do if I wanted to sum all plant counts in the below data set? How would you fix this data?</p>
<pre class="r"><code>berryessa_count &lt;- data.frame(
  locations = c(&quot;Stebbins&quot;, &quot;Quail Ridge&quot;, &quot;Putah Creek&quot;),
  `Foothill Pine` = c(109, 39, 12),
  `Manzanita` = c(84, 197, 15),
  `CA Bay Laurel` = c(94, 1092, 19)
)

berryessa_count</code></pre>
<pre><code>##     locations Foothill.Pine Manzanita CA.Bay.Laurel
## 1    Stebbins           109        84            94
## 2 Quail Ridge            39       197          1092
## 3 Putah Creek            12        15            19</code></pre>
<p>Answer:</p>
<pre class="r"><code>berryessa_count &lt;- reshape(
  # Wide data
  data = berryessa_count,
  # All the columns that need to be dissolved
  varying = names(berryessa_count)[2:length(berryessa_count)],
  # Name of new column with the groupings in `times`
  timevar = &quot;Spp.&quot;,
  # The groupings of plants
  times = names(berryessa_count)[2:length(berryessa_count)],
  # the name of the new column for the values
  v.names = &quot;Count&quot;,
  # From wide to long.
  direction = &quot;long&quot;
)

sum(berryessa_count$Count)</code></pre>
<pre><code>## [1] 1661</code></pre>
</div>
</div>
<div id="packages" class="section level1">
<h1>Packages</h1>
<p><strong>Key Concepts</strong></p>
<ul>
<li>Packages are like toolsets of code that other folks have created. Within each package contains a list of functions</li>
<li>You can install new packages by going to Tools &gt; Install Packages or typing in the code <code>install.packages(&quot;name of package here&quot;)</code>.</li>
<li>You always want to install the “dependencies”</li>
<li>On rare occasions, you will need install “dependencies” outside of R: this may include software like Java or some geographic library that has a more general purpose beyond R.</li>
</ul>
<hr />
<pre class="r"><code># First 20 functions in the package stats.
# You may recognize &quot;aggregate&quot;
head(ls(&quot;package:stats&quot;), n=20)</code></pre>
<pre><code>##  [1] &quot;acf&quot;                  &quot;acf2AR&quot;               &quot;add.scope&quot;           
##  [4] &quot;add1&quot;                 &quot;addmargins&quot;           &quot;aggregate&quot;           
##  [7] &quot;aggregate.data.frame&quot; &quot;aggregate.ts&quot;         &quot;AIC&quot;                 
## [10] &quot;alias&quot;                &quot;anova&quot;                &quot;ansari.test&quot;         
## [13] &quot;aov&quot;                  &quot;approx&quot;               &quot;approxfun&quot;           
## [16] &quot;ar&quot;                   &quot;ar.burg&quot;              &quot;ar.mle&quot;              
## [19] &quot;ar.ols&quot;               &quot;ar.yw&quot;</code></pre>
</div>
<div id="the-tidyverse" class="section level1">
<h1>The Tidyverse</h1>
<p><strong>Key Concepts</strong></p>
<ul>
<li>A suite of different packages designed for data scientists of all sorts wrangle their unwieldy data.</li>
<li>Conceptually, it is grounded on legible workflows, grouping data together in intuitive ways, and using these same processes across different packages.</li>
</ul>
<hr />
<pre class="r"><code># load the Tidyverse
library(tidyverse)</code></pre>
<div id="pipes" class="section level2">
<h2>Pipes</h2>
<p>Before we get into using some of the more important functions in the tidyverse, I wanted to introduce the pipe function from the <code>magrittr</code> package.</p>
<p>The pipe introduce a new form of function (that you’ve actually been using all along), infix functions. These functions don’t operate like <code>mean()</code>, which uses the name “mean” as a prefix in front of the parentheses. Instead, infix functions exist between two arguments. You’ve seen this with the <code>&lt;-</code> (assignment) operator, or in the addition of two values, eg <code>5 + 6</code>. The pipe is like one of these, sticking itself between two arguments.</p>
<p>The pipe operator, <code>%&gt;%</code> can be read in English as “then.” For instance, begin with a dataset, like iris, THEN give me the first 6 values.</p>
<pre class="r"><code># start with the R object of interests
iris %&gt;%
  # THEN use the function head() to see the first 6 values.
  head()</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
<div id="dplyr" class="section level2">
<h2>Dplyr</h2>
<p><strong>Key Concepts</strong></p>
<ul>
<li>A package to help you filter, sort, and clean data.</li>
</ul>
<hr />
<div id="filter" class="section level3">
<h3><code>filter</code></h3>
<p>Perhaps one of the most useful functions is <code>filter</code>.</p>
<pre class="r"><code>iris %&gt;%
  # get all of the rows for Iris virginica.
  filter(Species == &quot;virginica&quot;) %&gt;%
  head()</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 1          6.3         3.3          6.0         2.5 virginica
## 2          5.8         2.7          5.1         1.9 virginica
## 3          7.1         3.0          5.9         2.1 virginica
## 4          6.3         2.9          5.6         1.8 virginica
## 5          6.5         3.0          5.8         2.2 virginica
## 6          7.6         3.0          6.6         2.1 virginica</code></pre>
<pre class="r"><code>iris %&gt;%
  # get only virginica, with length between 5.5 &amp; 6 cm.
  filter(Species == &quot;virginica&quot; &amp; 
           Petal.Length &gt; 5.5 &amp; 
           Petal.Length &lt;= 6) %&gt;%
  # but has a petal with between 1.9-2.1 cm
  filter(Petal.Width &lt;= 2.1 &amp; Petal.Width &gt;= 1.9)</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 1          7.1         3.0          5.9         2.1 virginica
## 2          6.7         3.3          5.7         2.1 virginica
## 3          6.4         2.8          5.6         2.1 virginica</code></pre>
</div>
<div id="select" class="section level3">
<h3><code>select</code></h3>
<p>Another key function is <code>select</code> which picks columns you want.</p>
<pre class="r"><code>iris %&gt;%
  # select these two columns
  select(Petal.Length, Petal.Width) %&gt;%
  # I only want rows 1 through 6...
  # similar to head(), no?
  slice(1:6)</code></pre>
<pre><code>##   Petal.Length Petal.Width
## 1          1.4         0.2
## 2          1.4         0.2
## 3          1.3         0.2
## 4          1.5         0.2
## 5          1.4         0.2
## 6          1.7         0.4</code></pre>
</div>
<div id="mutate" class="section level3">
<h3><code>mutate</code></h3>
<p>What if we need to add a new column?</p>
<pre class="r"><code>iris %&gt;%
  # create a new column named &quot;has_big_petals&quot;
  # It should read TRUE if the petals are longer than 5
  # and wider than 2.4 cm.
  mutate(has_big_petals = (Petal.Length &gt; 5 &amp; 
                             Petal.Width &gt; 2.4)) %&gt;%
  head()</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species has_big_petals
## 1          5.1         3.5          1.4         0.2  setosa          FALSE
## 2          4.9         3.0          1.4         0.2  setosa          FALSE
## 3          4.7         3.2          1.3         0.2  setosa          FALSE
## 4          4.6         3.1          1.5         0.2  setosa          FALSE
## 5          5.0         3.6          1.4         0.2  setosa          FALSE
## 6          5.4         3.9          1.7         0.4  setosa          FALSE</code></pre>
<p>What if I need to add a new column, but say something other than <code>TRUE</code> and <code>FALSE</code>?</p>
<pre class="r"><code>iris %&gt;%
  # create a &quot;switch&quot; (another form of decision making)
  # where it stores the value to the right of the ~
  # if the expression on the left is TRUE.
  # Otherwise, store the value &quot;No, it does not.&quot;
  mutate(has_big_petals = case_when(
    (Petal.Length &gt; 5 &amp; Petal.Width &gt; 2.4) ~ &quot;Yes, it does.&quot;,
    T ~ &quot;No, it does not.&quot;
  )) %&gt;%
  head()</code></pre>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species   has_big_petals
## 1          5.1         3.5          1.4         0.2  setosa No, it does not.
## 2          4.9         3.0          1.4         0.2  setosa No, it does not.
## 3          4.7         3.2          1.3         0.2  setosa No, it does not.
## 4          4.6         3.1          1.5         0.2  setosa No, it does not.
## 5          5.0         3.6          1.4         0.2  setosa No, it does not.
## 6          5.4         3.9          1.7         0.4  setosa No, it does not.</code></pre>
<p>Where the above code reads “Yes, it does.” and “No, it does not.”, you could substitute anything, include a numeric value, like 1 and 0.</p>
</div>
<div id="group_by-summarize" class="section level3">
<h3><code>group_by</code> &amp; <code>summarize</code></h3>
<p>What if we want to get summaries by category?</p>
<pre class="r"><code>iris %&gt;%
  # pick your category
  group_by(Species) %&gt;%
  # What functions do you want to apply across a column?
  summarize(Count = n(), 
            `Mean Sepal Length` = mean(Sepal.Length),
            `Max Sepal Length` = max(Sepal.Length),
            `Med Sepal Length` = median(Sepal.Length)
            )</code></pre>
<pre><code>## # A tibble: 3 x 5
##   Species    Count `Mean Sepal Length` `Max Sepal Length` `Med Sepal Length`
##   &lt;fct&gt;      &lt;int&gt;               &lt;dbl&gt;              &lt;dbl&gt;              &lt;dbl&gt;
## 1 setosa        50                5.01                5.8                5  
## 2 versicolor    50                5.94                7                  5.9
## 3 virginica     50                6.59                7.9                6.5</code></pre>
</div>
<div id="arrange" class="section level3">
<h3><code>arrange</code></h3>
<p>What if you want to re-arrange the last example by the highest mean to lowest mean?</p>
<pre class="r"><code>iris %&gt;%
  # pick your category
  group_by(Species) %&gt;%
  # What functions do you want to apply across a column?
  summarize(Count = n(), 
            `Mean Sepal Length` = mean(Sepal.Length),
            `Max Sepal Length` = max(Sepal.Length),
            `Med Sepal Length` = median(Sepal.Length)
            ) %&gt;%
  # Would you like that in order?
  arrange(desc(`Mean Sepal Length`))</code></pre>
<pre><code>## # A tibble: 3 x 5
##   Species    Count `Mean Sepal Length` `Max Sepal Length` `Med Sepal Length`
##   &lt;fct&gt;      &lt;int&gt;               &lt;dbl&gt;              &lt;dbl&gt;              &lt;dbl&gt;
## 1 virginica     50                6.59                7.9                6.5
## 2 versicolor    50                5.94                7                  5.9
## 3 setosa        50                5.01                5.8                5</code></pre>
</div>
<div id="join-like-merge" class="section level3">
<h3><code>join</code> (like <code>merge</code>)</h3>
<p>There are multiple ways to “merge” or “join” two tables together using <code>dplyr</code>. Depending on how you want to join two tables, you may use one way or another. For instance, you might want to get rid of any rows that don’t match from one table to another, you my want all rows no matter what, etc. Below we use a <code>full_join</code>, which will create <code>NA</code> values for rows that don’t match, rather than dropping them entirely. For more information, I encourage you to check out the section on “Relational Data” in <a href="https://r4ds.had.co.nz/relational-data.html">R for Data Science</a>.</p>
<pre class="r"><code>iris_sepals %&gt;%
  full_join(x=.,
            y=iris_petals, 
            by = c(&quot;ID&quot;, 
                   &quot;Species&quot;)) %&gt;%
  head()</code></pre>
<pre><code>##    ID   Species Sepal.Length Sepal.Width Petal.Length Petal.Width
## 1 481 virginica          6.1         2.6          5.6         1.4
## 2 119    setosa          5.1         3.5          1.4         0.2
## 3 605 virginica          6.2         2.8          4.8         1.8
## 4 800 virginica          7.2         3.2          6.0         1.8
## 5 281 virginica          6.3         3.4          5.6         2.4
## 6 754    setosa          5.7         3.8          1.7         0.3</code></pre>
<p>What if the column names don’t match? No problem!</p>
<pre class="r"><code>iris_sepals %&gt;%
  # here we rename Species to spp in just iris_sepals
  rename(spp = Species) %&gt;%
  # now we just a join function, the same as above, except
  # the input value for `by`
  full_join(x=., 
            y=iris_petals, 
            # here we match by the ID column
            # and by both spp and Species columns.
            by = c(&quot;ID&quot;, 
                   &quot;spp&quot; = &quot;Species&quot;)) %&gt;%
  head()</code></pre>
<pre><code>##    ID       spp Sepal.Length Sepal.Width Petal.Length Petal.Width
## 1 481 virginica          6.1         2.6          5.6         1.4
## 2 119    setosa          5.1         3.5          1.4         0.2
## 3 605 virginica          6.2         2.8          4.8         1.8
## 4 800 virginica          7.2         3.2          6.0         1.8
## 5 281 virginica          6.3         3.4          5.6         2.4
## 6 754    setosa          5.7         3.8          1.7         0.3</code></pre>
<p>Compare to <code>merge</code> below:</p>
<pre class="r"><code>all_irises &lt;- merge(
  # first data.frame
  x = iris_sepals,
  # second data.frame
  y = iris_petals,
  # what are the &quot;keys?&quot;
  # i.e. what do they have in common.
  by = c(&quot;ID&quot;, &quot;Species&quot;),
  # This determines which data.frame is
  # considered the primary dataset.
  # When all = T, both are equally important.
  all = T
)</code></pre>
<p>What does <code>full_join</code> look like when we’re missing an observation in one of the tables?</p>
<pre class="r"><code>iris_sepals %&gt;%
  # here we make a subset using the first 149 values (of 150)
  slice(1:149) %&gt;%
  # now we do a full_join
  full_join(x=.,
            y=iris_petals, 
            by = c(&quot;ID&quot;, 
                   &quot;Species&quot;)) %&gt;%
  # let&#39;s look at the last 6 values to see the missing values
  # ID: 289 should be the one missing Sepal.Length &amp; Width.
  tail()</code></pre>
<pre><code>##      ID   Species Sepal.Length Sepal.Width Petal.Length Petal.Width
## 145 690    setosa          5.1         3.5          1.4         0.3
## 146 107 virginica          6.3         2.7          4.9         1.8
## 147 920 virginica          5.7         2.5          5.0         2.0
## 148 777 virginica          7.1         3.0          5.9         2.1
## 149 617    setosa          5.0         3.2          1.2         0.2
## 150 817    setosa           NA          NA          1.5         0.4</code></pre>
<p>Finally, take note that it doesn’t matter which table you begin with when you’re using <code>full_join</code>. We could begin with <code>iris_petals</code> instead of <code>iris_sepals</code> and all the code chunks above in this section would have had the same effect (albeit with the columns in a different order). However, this is the the case with join functions <code>left_join</code> and <code>right_join</code> which prioritize one table over the other. When using these latter functions, missing data is not filled in with <code>NA</code> values, but rather the whole row is excised.</p>
</div>
</div>
<div id="tidyr" class="section level2">
<h2>Tidyr</h2>
<p>The <code>tidyr</code> package contains tools similar to those addressed in the section above on “Data Prep.” However, unlike those <code>base</code> functions, the analogs in <code>tidyr</code> are easier to understand.</p>
<p><em>Supplemental</em></p>
<ul>
<li><a href="https://tidyr.tidyverse.org/articles/tidy-data.html">A Vignette on Tidy Data</a></li>
</ul>
<div id="pivot_wider" class="section level3">
<h3><code>pivot_wider</code></h3>
<pre class="r"><code># long to wide
untidy_iris %&gt;%
  pivot_wider(.,
              # the &quot;key&quot; variable(s)
              id_cols = c(&quot;ID&quot;, &quot;Species&quot;),
              # where the names of the new column come from
              names_from = Petal, 
              # where the values for those new columns are from
              values_from = Value) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##      ID Species Length Width
##   &lt;int&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt;
## 1     1 setosa     1.4   0.2
## 2     2 setosa     1.4   0.2
## 3     3 setosa     1.3   0.2
## 4     4 setosa     1.5   0.2
## 5     5 setosa     1.4   0.2
## 6     6 setosa     1.7   0.4</code></pre>
<p>Compare the above chunk to <code>reshape</code> below:</p>
<pre class="r"><code>reshape(
  # our untidy data
  data = untidy_iris,
  # the &quot;key&quot; variable(s)
  idvar = c(&quot;ID&quot;, &quot;Species&quot;),
  # the column that needs to change.
  timevar = &quot;Petal&quot;,
  # are we adding width to table?
  # or are we adding rows to the table?
  direction = &quot;wide&quot;
)</code></pre>
</div>
<div id="pivot_longer" class="section level3">
<h3><code>pivot_longer</code></h3>
<p>How about from wide to long?</p>
<pre class="r"><code>lob %&gt;%
  pivot_longer(.,
              # the &quot;key&quot; variable(s)
              # Here we use a helper function, starts_with
              # which picks any column starting with 3.
              # alternatively you can type each one of them,
              # eg, c(&quot;301&quot;, &quot;303&quot;, etc)
              # or
              # colnames(.)[2:length(.)]
              cols = starts_with(&quot;3&quot;),
              # where the names of the new column come from
              names_to = &quot;Seed&quot;, 
              # where the values for those new columns are from
              values_to = &quot;height&quot;) %&gt;%
  # reorder the columns
  select(height, age, Seed) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 3
##   height   age Seed 
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
## 1   4.51     3 301  
## 2   4.55     3 303  
## 3   4.79     3 305  
## 4   3.91     3 307  
## 5   4.81     3 309  
## 6   3.88     3 311</code></pre>
<p>Compare the above chunk to:</p>
<pre class="r"><code>lob2 &lt;- reshape(
  # Wide data
  data = lob,
  # All the columns that need to be dissolved
  varying = names(lob)[2:15],
  # Name of new column with the groupings in `times`
  timevar = &quot;Seed&quot;,
  # The groupings of Seed
  times = names(lob)[2:15],
  # the name of the new column for the values
  # that previously had no descriptor (just 301, etc)
  v.names = &quot;height&quot;,
  # From wide to long.
  direction = &quot;long&quot;
)</code></pre>
</div>
</div>
<div id="ggplot2" class="section level2">
<h2>ggplot2</h2>
<p>Data visualization is never easy in R and there are several different graphics packages for R, often differing based on the type of R object you’re trying to visualize. With this said, <code>ggplot2</code> is one of the more important graphics packages in R, and it is part of the <code>tidyverse</code>.</p>
<div id="one-discrete-variable" class="section level3">
<h3>One Discrete Variable</h3>
<div id="box-plot" class="section level4">
<h4>Box Plot</h4>
<pre class="r"><code># data
iris %&gt;%
  # call ggplot function
  # data = iris (hence the period)
  # x axis is Species (discrete variable in this case)
  # y axis is Sepal.Length
  # fill in the plot by Species (pick colors later)
  # Line color
  ggplot(data = ., 
         mapping = aes(x = Species, 
                       y = Sepal.Length, 
                       fill = Species,
                       color = &quot;#cc0066&quot;)) +
  # Make a boxplot
  geom_boxplot() +
  # Pick colors for fill.
  # color values in &quot;Hexadecimal,&quot; see Supplemental below.
  scale_fill_manual(values=c(&quot;#7a00cc&quot;, 
                             &quot;#cc00cc&quot;, 
                             &quot;#990099&quot;)) +
  # Re-label axes.
  labs(title = &quot;Boxplot of Sepal Lengths of Iris spp.&quot;,
       y = &quot;Sepal Length&quot;, 
       x = &quot;Iris spp.&quot;) +
  # Adjust legend: remove line color item.
  guides(colour = &quot;none&quot;) +
  # Center the title.
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Lab_Week2_files/figure-html/unnamed-chunk-80-1.png" /><!-- --></p>
</div>
<div id="bar-plot" class="section level4">
<h4>Bar Plot</h4>
<p>Differing from historgrams, bar plots are used where the x-axis is composed of discrete categories (much like box plots)</p>
<pre class="r"><code># data
iris %&gt;%
  # call ggplot function
  # data = iris (hence the period)
  # x axis is Species (discrete variable in this case)
  # y axis is Sepal.Length
  # fill in the plot by Species
  ggplot(data = ., 
         mapping = aes(x = Species, 
                       y = Sepal.Length, 
                       fill = Species)) +
  # Make a bar plot
  # Here we tell it to use a summary statistic.
  # Specifically, use the summary stat &quot;mean&quot; on y axis.
  geom_bar(stat = &quot;summary&quot;,
           fun.y = mean) +
  # Pick colors for fill.
  # color values in &quot;Hexadecimal,&quot; see Supplemental below.
  scale_fill_manual(values=c(&quot;#7a00cc&quot;, 
                             &quot;#cc00cc&quot;, 
                             &quot;#990099&quot;)) +
  # Re-label axes.
  labs(title =&quot;Bar Plot of Mean Sepal Lengths of Iris spp.&quot;,
       y = &quot;Mean Sepal Length&quot;, 
       x = &quot;Iris spp.&quot;) +
  # Black and White background
  theme_bw() +
  # Center the title.
  theme(plot.title = element_text(hjust = 0.5)) </code></pre>
<p><img src="Lab_Week2_files/figure-html/unnamed-chunk-81-1.png" /><!-- --></p>
</div>
</div>
<div id="one-continous-variable" class="section level3">
<h3>One Continous Variable</h3>
<div id="histogram" class="section level4">
<h4>Histogram</h4>
<p>Let’s look at frequency of measurements of Sepal Lengths for Iris setosa.</p>
<pre class="r"><code>iris %&gt;%
  filter(Species == &quot;setosa&quot;) %&gt;%
  ggplot(data = .,
         mapping = aes(x = Sepal.Length)) +
  geom_histogram(binwidth = 0.1)</code></pre>
<p><img src="Lab_Week2_files/figure-html/unnamed-chunk-82-1.png" /><!-- --></p>
</div>
<div id="frequency-polygons" class="section level4">
<h4>Frequency Polygons</h4>
<p>Below is a close relative histograms, frequency polygons.</p>
<pre class="r"><code>iris %&gt;%
  filter(Species == &quot;setosa&quot;) %&gt;%
  ggplot(data = .,
         mapping = aes(x = Sepal.Length)) +
  geom_freqpoly(binwidth = 0.1)</code></pre>
<p><img src="Lab_Week2_files/figure-html/unnamed-chunk-83-1.png" /><!-- --></p>
</div>
</div>
<div id="two-variables" class="section level3">
<h3>Two Variables</h3>
<p>Let’s see if there is a relationship between Sepal Length and Petal Length.</p>
<pre class="r"><code>iris %&gt;%
  ggplot(data = .,
         mapping = aes(x = Sepal.Length,
                       y = Petal.Length,
                       color = Species)) +
  geom_point()</code></pre>
<p><img src="Lab_Week2_files/figure-html/unnamed-chunk-84-1.png" /><!-- --></p>
</div>
<div id="stacking-graphics" class="section level3">
<h3>Stacking Graphics</h3>
<div id="lines-points" class="section level4">
<h4>Lines &amp; Points</h4>
<p>Relationship between Chick’s weight and age.</p>
<pre class="r"><code># data
ChickWeight %&gt;%
  # group by Diet
  # NOTE, only general mapping information is provided.
  # As I only want the first two layers to color by Diet.
  # The last line I want just black
  ggplot(data = ., 
         mapping = aes(x = Time,
                       y = weight)) +
  # draw points, colored by diet
  # note, most of mapping covered above, but not color.
  geom_point(size = 0.5, 
             mapping = aes(color = Diet)) +
  # draw mean for each diet.
  geom_line(stat = &quot;summary&quot;, 
            fun.y = &quot;mean&quot;,
            linetype = &quot;dashed&quot;,
            mapping = aes(color = Diet)) +
  # draw overall mean
  # note, we excluded
  geom_line(stat = &quot;summary&quot;,
            fun.y = &quot;mean&quot;,
            size = 1,
            color = &quot;black&quot;) +
  # BW background
  theme_bw()</code></pre>
<p><img src="Lab_Week2_files/figure-html/unnamed-chunk-85-1.png" /><!-- --></p>
</div>
<div id="area-plots" class="section level4">
<h4>Area Plots</h4>
<p>Using New York’s 1973 <code>airquality</code> dataset. Let’s look at a few variables like Ozone &amp; Temperature by Date.</p>
<pre class="r"><code>aq %&gt;%
  ggplot(data = .,
         mapping = aes(x = Date)) +
  # Temperature, cerulean
  geom_area(mapping = aes(y = Temp),
            fill = &quot;#0099ff&quot;) +
  # Ozone, eggplant
  geom_area(mapping = aes(y = Ozone), 
            fill = &quot;#660066&quot;, 
            alpha = 0.7) +
  labs(y = &quot;Temperature (F) | Ozone (ppb) &quot;)</code></pre>
<pre><code>## Warning: Removed 37 rows containing missing values (position_stack).</code></pre>
<p><img src="Lab_Week2_files/figure-html/unnamed-chunk-87-1.png" /><!-- --></p>
<p><em>Supplemental</em></p>
<ul>
<li><a href="https://rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf">ggplot2 Cheat Sheet</a></li>
<li><a href="https://ggplot2.tidyverse.org/reference/index.html">ggplot2 Reference</a></li>
<li>Need help picking a color? <a href="https://www.w3schools.com/colors/colors_picker.asp">HTML Color Picker</a></li>
</ul>
</div>
</div>
</div>
<div id="the-rest-of-the-tidyverse" class="section level2">
<h2>The Rest of the Tidyverse</h2>
<p>There are other useful <code>tidyverse</code> packages that we do not explore here. We can mimic the apply family of functions with <code>purrr</code>, maniuplate factors with <code>forcats</code>, and perhaps one of the most useful packages we do not cover in depth here is <code>stringr</code>, which streamlines a lot issues with maniuplating text and using regular expressions (aka regex). Ever wonder how to extract bits of text from a longer string? You can use regex for that. There are <code>base</code> regex functions like <code>grepl</code>, but often it’s faster to use <code>stringr</code>.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>


</body>
</html>
