---
title: "Lab Lecture 7"
author: "Kenji Tomari"
output: 
  html_document:
    theme: readable
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Spatial Heterogeneity

## Question 1

To answer this question, it's useful to look at Chi & Zhu's example of interaction variables starting on page 118 with the first full paragraph. In Chi & Zhu's example, the regions are designated as rural, urban, or suburban and the model uses rural as the reference group (see Table 5.2); the variable with which those regions are interacting is land developability (as opposed to `medage` for us). While the reference group can be changed, by default it looks like our model's reference group is the East Bay region (note its conspicuous absence in the `summary` results).

If you're new to the concept of the interaction effect, you should take note that this is a more general concept in linear regression, not limited to this geographic use-case. If you're interested in learning more broadly about interaction effects, you can read this [article](https://statisticsbyjim.com/regression/interaction-effects/) by StatisticsByJim, or read ISLR's explanation of interaction effects on p 87, titled, "Removing the Additive Assumption."

## Question 2

Chi & Zhu's example of stratified models begins on p. 120 in the first full paragraph; stratified models are described in more depth on p. 116, check it out!

## Question 3

When you're comparing the differences and similarities of these coefficients, consider some of the issues with both interaction and partition/stratified models. Those issues are discussed in section 5.2.1 on p 122 of Chi & Zhu in the first three paragraphs. In the last full paragraph on p 124, Chi & Zhu describe where the spatial regime models are the same as the interaction and partition/stratified models. In answering this question, you should present your analysis as Chi & Zhu do on p. 126, in section 5.2.3, in paragraph 3, but reporting and comparing the values for our three linear models.

By the way, you should note that the coefficient "medage:regionSouth Bay" in the interacted model is written that way because we specified the `lm` function with `medage*region`, but you get the same values if you do `region*medage` and then the coefficient label reads "regionSouth Bay:medage". So, don't get tripped up about the label itself being in a different order in the `summary` output.

Finally, this section in Chi & Zhu talks about testing for "structural stability" in the model, but this term isn't well defined in the textbook. See the below description by Dr. Shalabh. Much as autoregressive models (like SEM/SLM) were developed to look at time lags (and not spatial lags), read the below description of structual stability replacing space for time.  

What is *Structural Stability*?

> "A fundamental assumption in regression modeling is that the pattern of data on dependent and independent variables  remains  the  same  throughout  the  period  over  which  the  data  is  collected.  Under  such  an assumption, a single linear regression model is fitted over the entire data set. The regression model is estimated and used for prediction assuming that the parameters remain same over the entire time period of estimation and prediction. When it is suspected that there exists a change in the pattern of data, then the fitting of single linear regression model may not be appropriate, and more than one regression models may be required to be fitted. Before taking such a decision to fit a single or more than one regression models, a question arises how to test and decide if there is a change in the structure or pattern of data. Such changes can be characterized by the change in the parameters of the model and are termed as structural change." ([Shalabh](http://home.iitk.ac.in/~shalab/econometrics/Chapter12-Econometrics-TestsforStructuralChangeandStability.pdf), more resources [here](http://home.iitk.ac.in/~shalab/course3.htm))

## Question 4

Use the code directly above Question 4, beginning AFTER you get the `dfree` to make your map. Just take note that you need to replace relevant variable names (i.e. anything that says "parks") with "medage". You don't need to re-assign/re-create the `breaks` since they are just general alpha/significance levels. So, by the end, you should have a new column in `bayarea` for `medage.t` and `medage.t.p`, and you should have changed the `col` argument in `tm_polygon` and the main title of the map. At the end, you should have a map depicting the statistical signifiance of the spatially heterogenous effect of median age on median housing values in the [Yay](https://en.wikipedia.org/wiki/My_Ghetto_Report_Card#Track_listing). You can model your answer after Chi & Zhu's second full paragraph on p. 134, where they discuss the statistical signifance of  GWR on their Wisconsin dataset.