<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Professor Noli Brazil" />

<meta name="date" content="2024-05-06" />

<title>Point Pattern Analysis</title>

<script src="site_libs/header-attrs-2.22/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
      .display.math{display: block; text-align: center; margin: 0.5rem auto;}
  </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">GEO 200CN: Spring 2024</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
<li>
  <a href="hw_guidelines.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Labs
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="getting_started.html">Getting Started</a>
    </li>
    <li>
      <a href="eda.html">Exploratory Data Analysis</a>
    </li>
    <li>
      <a href="inference.html">Statistical Inference</a>
    </li>
    <li>
      <a href="hypothesis.html">Hypothesis Testing</a>
    </li>
    <li>
      <a href="linearregression.html">Linear Regression</a>
    </li>
    <li>
      <a href="linearregression2.html">More Linear Regression</a>
    </li>
    <li>
      <a href="logistic.html">Logistic Regression</a>
    </li>
    <li>
      <a href="introspatial.html">Intro to Spatial Data</a>
    </li>
    <li>
      <a href="pointpatterns.html">Point Pattern Analysis</a>
    </li>
    <li>
      <a href="spatialautocorrelation.html">Spatial Autocorrelation</a>
    </li>
    <li>
      <a href="spatialreg.html">Spatial Regression</a>
    </li>
    <li>
      <a href="prediction.html">Prediction Modelling</a>
    </li>
    <li>
      <a href="variableselection.html">Variable Selection</a>
    </li>
    <li>
      <a href="interpolation.html">Spatial Interpolation</a>
    </li>
    <li>
      <a href="kriging.html">Kriging</a>
    </li>
    <li>
      <a href="regtrees.html">Regression Trees</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="tips.html">R Tips</a>
    </li>
    <li>
      <a href="data_wrangling.html">Data Wrangling</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Point Pattern Analysis</h1>
<h3 class="subtitle"><font size="4">GEO 200CN - Quantitative
Geography</font></h3>
<h4 class="author">Professor Noli Brazil</h4>
<h4 class="date">May 6, 2024</h4>

</div>


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: normal;
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>
<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>
<p><br />
</p>
<p>The fundamental building blocks of vector or object data are points.
As such, we start our journey into spatial data analysis by going
through the basic methods for examining point patterns. This guide
follows closely OSU Chapter 5. The objectives of the guide are as
follows</p>
<ol style="list-style-type: decimal">
<li>Learn <strong>spatstat</strong> package functions for setting up
point data for analysis</li>
<li>Learn first-order or density based measures for examining point
patterns</li>
<li>Learn second-order or distance based measures for examining point
patterns</li>
</ol>
<p>To help us accomplish these learning objectives, we will be examining
crime in a nondescript city.</p>
<div style="margin-bottom:25px;">

</div>
<div id="installing-and-loading-packages" class="section level2">
<h2><strong>Installing and loading packages</strong></h2>
<p><br />
</p>
<p>We’ll be using a couple of new packages in this lab. First, install
<strong>spatstat</strong> using <code>install.packages()</code>.</p>
<pre class="r"><code>install.packages(&quot;spatstat&quot;)</code></pre>
<p>Next, install <strong>rspat</strong> using the following code. We
download <strong>rspat</strong> from Github because it is not available
on CRAN yet. Install the <strong>remotes</strong> package if you don’t
already have it, and then use the function <code>install_github()</code>
to download it from Github.</p>
<pre class="r"><code>if (!require(&quot;rspat&quot;)) remotes::install_github(&#39;rspatial/rspat&#39;)</code></pre>
<p>Finally, load these and other required packages for this lab using
the function <code>library()</code></p>
<pre class="r"><code>library(spatstat)
library(rspat)
library(sf)
library(tidyverse)</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="why-point-pattern-analysis" class="section level2">
<h2><strong>Why point pattern analysis?</strong></h2>
<p><br />
</p>
<p>Point data give us the locations of objects or events within an area.
Objects can be things like trees or where an animal was last seen. They
can also be houses, street lights or even people, such as the locations
of where people were standing during a protest. Events can be things
like the epicenter of an earthquake or where a wildfire was ignited.
They can also be crimes or where someone tweeted something. Point
pattern analysis can answer such questions like:</p>
<ol style="list-style-type: decimal">
<li>What is the density of a process? If you work on crime, you may want
to find out where crime is concentrated. If you work in public health,
you might want to know where the density of cholera deaths are
highest.</li>
<li>How are points distributed across space? If you are a plant
scientist, perhaps you are curious as to whether an invasive species is
randomly dispersed or clustered across a study area.</li>
<li>Are events or objects influencing the location of other similar
events or objects? Back to our crime example, you might be interested in
whether a crime will trigger future crimes to occur in the same area,
following a contagion effect.</li>
<li>Do (1)-(3) differ across some characteristic? You might be
interested in whether certain crimes are more clustered than others so
that you can employ different safety programs more efficiently.</li>
</ol>
<p>You can also examine whether the density of your points covary or are
influenced by other processes - such as species density and
elevation.</p>
<p>Our research questions in this lab are: Does crime cluster in a
nondescript American city? Does clustering vary by type of crime?</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="bringing-in-the-data" class="section level2">
<h2><strong>Bringing in the data</strong></h2>
<p><br />
</p>
<p>We will be using datasets from the <strong>rspat</strong> package.
Specifically, we bring in crime locations and the city boundaries. Bring
these data in using the function <code>spat_data()</code>.</p>
<pre class="r"><code>city &lt;- spat_data(&quot;city&quot;)
crime &lt;- spat_data(&quot;crime&quot;)</code></pre>
<p><em>city</em> is an <em>SpatVector</em> spatial polygon object
containing the boundaries of a city. <em>crime</em> is an
<em>SpatVector</em> spatial points object containing crimes in the city.
To see what we got, plot the city boundaries and the crime points.</p>
<pre class="r"><code>par(mai=c(0,0,0,0))
plot(city, col=&#39;light blue&#39;)
points(crime, col=&#39;red&#39;, cex=.5, pch=&#39;+&#39;)</code></pre>
<p><img
src="pointpatterns_files/figure-html/unnamed-chunk-5-1.png" /><!-- --></p>
<p>Does this city look familiar to you?</p>
<p>All point pattern analysis tools used in this lab guide are available
in the <strong>spatstat</strong> package. These tools are designed to
work with points stored as <em>ppp</em> objects and not
<em>SpatVector</em> or <em>sf</em> objects. So, yes, another spatial
object to learn about. We won’t go through the nuts and bolts of how
<em>ppp</em> objects work. We’ll cover what is only necessary for
running our analyses.</p>
<p>We need to convert our <strong>SpatVector</strong> <em>crime</em>
points object into a <em>ppp</em> object. To do this, we have to first
convert it to an <strong>sf</strong> object using the function
<code>st_as_sf()</code> because we can’t convert a
<strong>SpatVector</strong> directly into a <em>ppp</em> object.</p>
<pre class="r"><code>crime.sf &lt;- st_as_sf(crime)</code></pre>
<p>Then convert the object to a <em>ppp</em> object using the function
<code>as.ppp()</code>. We have to provide point coordinates and the
observation window. Below we obtain the coordinates of the
<strong>sf</strong> object in matrix form with
<code>st_coordinates()</code>, and consider the observation window as
the bounding box of the crime data which can be obtained with
<code>st_bbox()</code>. A bounding box can be used to define any area on
a map. It is commonly used by mapping applications to determine which
map features within a certain area should be displayed on a given
map.</p>
<pre class="r"><code>crime.ppp &lt;- as.ppp(st_coordinates(crime.sf), st_bbox(crime.sf))</code></pre>
<p>As we defined above, point data give the location of objects or
events within an area. In addition to coordinates, points have other
data attached to them called marks. Marks are essentially attributes of
the point (i.e. species of tree, type of crime). Marks could be
categorical (type of crime) or continuous (diameter of tree). Right now
the <em>crime.ppp</em> object contains no attribute or <em>marks</em>
information. We’ll add marks later in the guide.</p>
<pre class="r"><code>marks(crime.ppp)</code></pre>
<pre><code>## NULL</code></pre>
<p>Point pattern analyses should have their study boundaries explicitly
defined. This is the window through which we are observing the points.
One example is the boundaries of a forest if you are studying tree
species distribution. In the current example, it is the boundaries of
our nondescript city. <strong>spatstat</strong> uses a special boundary
object - an <em>owin</em>, which stands for observation window. We will
need to coerce <em>city</em> to an object of class <em>owin</em> using
the function <code>as.owin()</code>. Before we do so, we have to convert
the <em>SpatVector</em> <em>city</em> into an <strong>sf</strong>
object.</p>
<pre class="r"><code>city.sf &lt;- st_as_sf(city)
cityOwin &lt;- as.owin(city.sf)
class(cityOwin)</code></pre>
<pre><code>## [1] &quot;owin&quot;</code></pre>
<p>To set or “bind” the city boundary <em>owin</em> to the
<em>crime.ppp</em> point feature object, use the <code>Window()</code>
function, which is a <strong>spatstat</strong> function.</p>
<pre class="r"><code>Window(crime.ppp) &lt;- cityOwin</code></pre>
<p>We’re now set and ready to roll. Let’s do some analysis!</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="centrography" class="section level2">
<h2><strong>Centrography</strong></h2>
<p><br />
</p>
<p>Before considering more complex approaches, let’s compute the mean
center and standard distance for the crime data as described on page 125
of OSU. To calculate these values, you’ll need to extract the x and y
coordinates from the <em>crime.ppp</em> object using the
<strong>spatstat</strong> function <code>coords()</code></p>
<pre class="r"><code>xy &lt;- coords(crime.ppp)</code></pre>
<p>And then compute the mean center following equation 5.1 on page 125.
We’ll use our friend <code>summarize()</code> to help us out here.</p>
<pre class="r"><code># mean center
mc &lt;- xy %&gt;%
        summarize(xmean = mean(x), 
                  ymean = mean(y))
mc</code></pre>
<pre><code>##     xmean   ymean
## 1 6635644 1962882</code></pre>
<p>And then standard distance using equation 5.2 on page 125.</p>
<pre class="r"><code># standard distance
sd &lt;- sqrt(sum((xy$x- mc$xmean)^2 + (xy$y - mc$ymean)^2) / nrow(xy))
sd</code></pre>
<pre><code>## [1] 7130.572</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="density-based-measures" class="section level2">
<h2><strong>Density based measures</strong></h2>
<p><br />
</p>
<p>Centrography is rather dull because it ignores spatial variation in
the data. Instead, we can explicitly examine the distribution of points
across a geographic area. This is measuring first-order effects or
examining point density. First-order effects or patterns look at trends
over space.</p>
<div style="margin-bottom:25px;">

</div>
<div id="overall-density" class="section level3">
<h3><strong>Overall density</strong></h3>
<p><br />
</p>
<p>The overall density given in equation 5.3 in OSU on page 126 can be
calculated as follows</p>
<pre class="r"><code>CityArea &lt;- expanse(city)
nrow(xy) / CityArea</code></pre>
<pre><code>## [1] 0.0001027119</code></pre>
<p>The command <code>expanse(city)</code> calculates the area (in feet
squared) of our city, which represents the value <em>a</em> in formula
5.3. <code>nrow(xy)</code> represents the number of crimes in the city,
which represents the value <em>n</em>.</p>
<p>Overall density is a little bit better than the centrography
measures, but it is still a single number, and thus we can do better. As
OSU states on page 127, we lose a lot of information when we calculate a
single summary statistic. Let’s go through the two “local” density
approaches covered in OSU: Quadrat and Kernel density.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="quadrat-counts" class="section level3">
<h3><strong>Quadrat counts</strong></h3>
<p><br />
</p>
<p>A basic yet descriptively useful visualization of point density is to
create a grid (often called quadrats) of your study area and count the
number of crimes in each grid cell. To compute quadrat counts (as on
p.127-130 in OSU), use <strong>spatstat</strong>’s
<code>quadratcount()</code> function. The following code chunk divides
the city boundary into a grid of 3 rows and 6 columns and tallies the
number of points falling in each quadrat.</p>
<pre class="r"><code>qcounts1 &lt;- quadratcount(crime.ppp, nx= 6, ny=3)</code></pre>
<p>The object <em>qcounts1</em> stores the number of points inside each
quadrat. You can plot the quadrats along with the counts as follows:</p>
<pre class="r"><code>plot(crime.ppp, pch=20, cols=&quot;grey70&quot;, main=NULL) 
plot(qcounts1, add=TRUE)</code></pre>
<p><img
src="pointpatterns_files/figure-html/unnamed-chunk-16-1.png" /><!-- --></p>
<p>Wow, 582 crimes in that one bottom cell. That place must be
<em>really</em> dangerous. Three-by-six might be too small. Let’s
instead make a 15 by 30 grid.</p>
<pre class="r"><code>qcounts2 &lt;- quadratcount(crime.ppp, nx= 30, ny=15)</code></pre>
<p>then plot</p>
<pre class="r"><code>plot(crime.ppp, pch=20, cols=&quot;grey70&quot;, main=NULL)  # Plot points
plot(qcounts2, add=TRUE)  # Add quadrat grid. </code></pre>
<p><img
src="pointpatterns_files/figure-html/unnamed-chunk-18-1.png" /><!-- --></p>
<p>In real life one should always try a range of row and column sizes to
get a sense of how sensitive the results are (this is trying to deal
with the “Bad News” OSU item Scale).</p>
<p>We’ll need to convert the resulting <em>qcounts2</em> object into a
data frame to calculate the variance-mean ratio (VMR) described on page
130 in OSU.</p>
<pre class="r"><code>Qcount&lt;-data.frame(qcounts2)</code></pre>
<p>And the VMR is</p>
<pre class="r"><code>var(Qcount$Freq)/mean(Qcount$Freq)</code></pre>
<pre><code>## [1] 32.25635</code></pre>
<p><br></p>
<p class="comment">
<strong>Question 1</strong>: Explain why a VMR greater than 1 indicates
spatial clustering.
</p>
<p><br></p>
<div style="margin-bottom:25px;">

</div>
<div id="hypothesis-testing" class="section level4">
<h4><strong>Hypothesis testing</strong></h4>
<p><br />
</p>
<p>As OSU states on page 142- “It is one thing to create an index such
as [the VMR]. but it is quite another to generate a significance test
that answers the basic question posed at the bottom of Figure 5.14 (What
can we infer about the process from the statistics?).</p>
<p>We can employ the Chi-square test for spatial randomness that OSU
describes on page 142-43 using the handy dandy
<code>quadrat.test()</code> function. The default is the Chi-square
test, but you can run the Monte Carlo test described on page 148 using
<code>method = MonteCarlo</code>.</p>
<pre class="r"><code>quadrat.test(crime.ppp, nx= 30, ny=15)</code></pre>
<pre><code>## 
##  Chi-squared test of CSR using quadrat counts
## 
## data:  crime.ppp
## X2 = 8022.1, df = 295, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## 
## Quadrats: 296 tiles (irregular windows)</code></pre>
<p><br></p>
<p class="comment">
<strong>Question 2</strong>: What are the null and alternative
hypotheses for this test? What does the VMR score combined with the
chi-square test tell us about the point pattern?
</p>
<p><br></p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="kernel-density" class="section level3">
<h3><strong>Kernel density</strong></h3>
<p><br />
</p>
<p>The kernel density approach is an extension of the quadrat method:
Like the quadrat density, the kernel approach computes a localized
density for subsets of the study area, but unlike its quadrat density
counterpart, the sub-regions overlap one another providing a moving
sub-region window.</p>
<p>The <strong>spatstat</strong> package has a function called
<code>density.ppp()</code> that computes a kernel density estimate of
the point pattern. A discussion of kernel density maps is located in
page 68-71 in OSU. That discussion points to two tuning parameters that
are important to consider when creating a kernel density map: the
bandwidth, which controls the size and shape of the radius, and the
kernel function, which controls how point counts are smoothed. We can
just accept the defaults and get the following map.</p>
<pre class="r"><code>ds &lt;- density.ppp(crime.ppp)
par(mai=c(0,0,0.5,0.5))
plot(ds, main=&#39;crime density&#39;)</code></pre>
<p><img
src="pointpatterns_files/figure-html/unnamed-chunk-22-1.png" /><!-- --></p>
<p>We can alter the bandwidth using the <code>sigma =</code> argument. A
really large <code>sigma</code> makes the map too smooth</p>
<pre class="r"><code>ds &lt;- density.ppp(crime.ppp, sigma = 10000)
par(mai=c(0,0,0.5,0.5))
plot(ds, main=&#39;crime density&#39;)</code></pre>
<p><img
src="pointpatterns_files/figure-html/unnamed-chunk-23-1.png" /><!-- --></p>
<p>A small <code>sigma</code> creates a map that captures really
localized clusters</p>
<pre class="r"><code>ds &lt;- density.ppp(crime.ppp, sigma = 1000)
par(mai=c(0,0,0.5,0.5))
plot(ds, main=&#39;crime density&#39;)</code></pre>
<p><img
src="pointpatterns_files/figure-html/unnamed-chunk-24-1.png" /><!-- --></p>
You can also change the kernel function by specifying
<code>kernel =</code> to one of four options “gaussian” (the default),
“epanechnikov”, “quartic” or “disc”.
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="distance-based-measures" class="section level2">
<h2><strong>Distance based measures</strong></h2>
<p><br />
</p>
<p>An alternative to density based methods are distance based methods
whereby the interest lies in how the points are distributed relative to
one another (a second-order property of the point pattern) as opposed to
how the points are distributed relative to the study’s extent.</p>
<div style="margin-bottom:25px;">

</div>
<div id="mean-nearest-neighbor-distance" class="section level3">
<h3><strong>Mean Nearest-Neighbor Distance</strong></h3>
<p><br />
</p>
<p>The first distance-based method that OSU goes through is calculating
the mean nearest neighbor (MNN) distance. Here, you calculate for each
point the distance to its nearest neighbor. You do this using the
function <code>nndist()</code>, which is a part of the
<strong>spatstat</strong> package.</p>
<pre class="r"><code>nn.p &lt;- nndist(crime.ppp, k=1)</code></pre>
<p>We plug <em>crime.ppp</em> into <code>nndist()</code>, resulting in a
numeric vector containing the distance to each nearest neighbor
(<code>k=1</code> specifies distance just to the nearest neighbor. Try
<code>k=</code> some other number and see what you get) for each
point.</p>
<pre class="r"><code>head(nn.p)</code></pre>
<pre><code>## [1]   0.0000   0.0000   0.0000 140.8069   0.0000   0.0000</code></pre>
<p>We find that the nearest crime to the crime in the 4th row of
<em>crime.ppp</em> is 140.8069 feet. We need to take the mean to get the
mean nearest neighbor</p>
<pre class="r"><code>mnn.p &lt;- mean(nn.p)
mnn.p</code></pre>
<pre><code>## [1] 53.7598</code></pre>
<p>The mean nearest neighbor distance of 53.7598 feet (check
<code>st_crs(crime)</code> to find how we got feet as the units of
distance).</p>
<div style="margin-bottom:25px;">

</div>
<div id="hypothesis-testing-1" class="section level4">
<h4><strong>Hypothesis testing</strong></h4>
<p><br />
</p>
<p>The value 53.7598 seems small, indicating that crime clusters. But,
we can formally test this using the Clark and Evan’s R statistic
described on OSU page 143. The <strong>spatstat</strong> package has the
function <code>clarkevans.test()</code> for calculating this
statistic.</p>
<pre class="r"><code>clarkevans.test(crime.ppp)</code></pre>
<pre><code>## 
##  Clark-Evans test
##  CDF correction
##  Z-test
## 
## data:  crime.ppp
## R = 0.30992, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided</code></pre>
<p><br></p>
<p class="comment">
<strong>Question 3</strong>: What do the Clark Evans test results tell
us about the point pattern? Explain why an R less than 1 indicates
spatial clustering?
</p>
<p><br></p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="distance-functions" class="section level3">
<h3><strong>Distance Functions</strong></h3>
<p><br />
</p>
<p>The F, G, K and L functions are discussed on pages 145-148 in OSU.
Our new friend <strong>spatstat</strong> provides canned functions for
estimating these distributions.</p>
<p>The K-function summarizes the distance between points for all
distances. The calculation of K consists of dividing the mean of the sum
of the number of points at different distance lags for each point by the
area’s density.</p>
<p>To compute the K function, use the function <code>Kest()</code>.</p>
<pre class="r"><code>K &lt;- Kest(crime.ppp)</code></pre>
<p>Then plot it like on page 146 in OSU.</p>
<pre class="r"><code>par(mfrow=c(1,1))
plot(K)</code></pre>
<p><img
src="pointpatterns_files/figure-html/unnamed-chunk-30-1.png" /><!-- --></p>
<p>The plot returns different estimates of K depending on the edge
correction chosen. By default, the isotropic, translate and border
corrections are implemented. Edge corrections are discussed on pages
137-139 in OSU.</p>
<p>Unsurprisingly, to calculate the G, F and L functions, use the
functions <code>Gest()</code>, <code>Fest()</code>, and
<code>Lest()</code>, respectively, which take on the same form as
<code>Kest()</code>.</p>
<p>OSU discusses calculating envelopes around the functions to examine
whether the observed functions are simply due to chance. Use the
<code>envelope()</code> function to create the envelopes. Here, we use
49 Monte Carlo simulations. This might take some time, so kick back a
bit, and grab a cool be…, errr, i mean a glass of organic non-GMO
electrolyte coconut water (no offense if you like this, it’s all
good).</p>
<pre class="r"><code>#takes awhile
envK &lt;- envelope(crime.ppp, fun = Kest, nsim = 49)
plot(envK)</code></pre>
<p><img
src="pointpatterns_files/figure-html/unnamed-chunk-31-1.png" /><!-- --></p>
<p>It’s hard to see, but R is plotting the envelopes. They are just
really narrow. The default envelopes are the maximum and minimum values.
This is set by <code>nrank</code> in <code>envelope()</code>, which is
<code>nrank=1</code>. This means your confidence interval is</p>
<pre class="r"><code>1-(2/50)</code></pre>
<pre><code>## [1] 0.96</code></pre>
<p>The highest and lowest gives you two. And there are 50 K functions
(49 simulations + observed K). Hence 2/50. Subtract by 1 to get the
confidence level. OSU talks about the disadvantages of a simulation
approach for computationally intensive calculations on page 151.</p>
<p>Replace <code>Kest</code> with <code>Gest</code>, <code>Fest</code>,
and <code>Lest</code> to get envelopes for the other alphabet
functions.</p>
<p><br></p>
<p class="comment">
<strong>Question 4</strong>: Calculate the F and G functions. Interpret
the results.
</p>
<p><br></p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="marked-data" class="section level2">
<h2><strong>Marked Data</strong></h2>
<p><br />
</p>
<p>Marked data means data points with attributes. Like the height of a
tree for tree points. In the crime data, we have a categorical variable
indicating type of crime. As I mentioned in the beginning of our journey
today, we are not going to do extensive work with marked point pattern
analyses, but let’s do a little just to whet the appetite. For example,
does the extent of clustering vary by crime type?</p>
<p>We have to go back to the <em>crime</em> <strong>sf</strong> object
to create a marked crime <em>ppp</em> object. If your marks are
categorical, make sure they are stored as factors in your <em>ppp</em>
object. In our case, <em>CATEGORY</em> classifies each crime by its
type.</p>
<pre class="r"><code>table(crime.sf$CATEGORY)</code></pre>
<pre><code>## 
##                Arson             Assaults           Auto Theft 
##                    9                  172                   86 
##  Commercial Burglary   Drugs or Narcotics      Drunk in Public 
##                  143                  134                  232 
##                  DUI          Grand Theft          Hate Crimes 
##                  212                  143                    6 
##          Petty Theft Residential Burglary              Robbery 
##                  665                  219                   49 
##            Vandalism     Vehicle Burglary              Weapons 
##                  355                  221                   15</code></pre>
<p>Is it a factor?</p>
<pre class="r"><code>class(crime.sf$CATEGORY)</code></pre>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Make it a factor using <code>as.factor()</code>, and save it in a new
variable <em>cat</em>.</p>
<pre class="r"><code>crime.sf$fcat &lt;- as.factor(crime.sf$CATEGORY)</code></pre>
<p>Convert to <em>ppp</em>, set the mark, and set the window</p>
<pre class="r"><code>crime2.ppp &lt;- as.ppp(st_coordinates(crime.sf), st_bbox(crime.sf))
marks(crime2.ppp) &lt;- as.factor(crime$CATEGORY)
Window(crime2.ppp) &lt;- cityOwin</code></pre>
<p>We can automatically split <em>mpp</em> by crime type using the
<code>split.ppp()</code> function</p>
<pre class="r"><code>spp &lt;- split.ppp(crime2.ppp)</code></pre>
<p>We can plot arsons</p>
<pre class="r"><code>plot(spp$Arson, main = &quot;Arsons&quot;)</code></pre>
<p><img
src="pointpatterns_files/figure-html/unnamed-chunk-38-1.png" /><!-- --></p>
<p><br></p>
<p class="comment">
<strong>Question 5</strong>: Using the <em>spp</em> object we created,
use one first order and one second order method to compare the
clustering of crime across the following types: Residential Burglary,
Auto Theft, Drunk in Public, and Assaults. Summarize your results.
</p>
<p><br></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="resources" class="section level2">
<h2><strong>Resources</strong></h2>
<p><br />
</p>
<p>The procedures in this lab heavily relies on the
<strong>spatstat</strong> package, which is very well <a
href="https://spatstat.org/">documented</a>. Paula Moraga’s <a
href="https://www.paulamoraga.com/book-spatial/spatial-point-patterns.html">book</a>
has a few great chapters on spatial point patterns.</p>
<hr />
<p><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This
work is licensed under a
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative
Commons Attribution-NonCommercial 4.0 International License</a>.</p>
<p>Website created and maintained by <a
href="https://nbrazil.faculty.ucdavis.edu/">Noli Brazil</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>


</body>
</html>
